#!/usr/bin/env python3
"""
Finite-dimensional Laplacian on a truncated idele-class model.

Local: graph Laplacian on a cycle per prime (mesh m), tensor sum on the product.
Global: GL(1) Hecke constraint — Fourier modes with a single angular frequency
  omega_p = 2*pi*n_p/log(p) equal across all p in S (adelic character consistency).

The unconstrained direct-sum spectrum is the full Fourier multiset (dense near 0).
The constrained quotient spectrum is the frequency-locked subspace (sparse, gamma-scale).
"""
from __future__ import annotations

import argparse
import heapq
import json
import math
from pathlib import Path
from typing import Iterator

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
TRACES = ROOT / "traces"


def sieve(n: int) -> list[int]:
    if n < 2:
        return []
    is_p = [True] * (n + 1)
    is_p[0] = is_p[1] = False
    for i in range(2, int(n**0.5) + 1):
        if is_p[i]:
            for j in range(i * i, n + 1, i):
                is_p[j] = False
    return [i for i, v in enumerate(is_p) if v]


def load_zeros(n: int) -> list[float]:
    out: list[float] = []
    with open(ROOT / "odlyzko_zeros2m.txt") as f:
        for i, line in enumerate(f):
            if i >= n:
                break
            line = line.strip()
            if line:
                out.append(float(line))
    return out


def flat_index(dims: list[int], idx: tuple[int, ...]) -> int:
    flat = 0
    stride = 1
    for d, i in zip(dims, idx):
        flat += i * stride
        stride *= d
    return flat


def unravel(flat: int, dims: list[int]) -> tuple[int, ...]:
    out: list[int] = []
    for d in dims:
        out.append(flat % d)
        flat //= d
    return tuple(out)


def cycle_laplacian(m: int) -> np.ndarray:
    l = np.zeros((m, m), dtype=np.float64)
    for i in range(m):
        l[i, i] = 2.0
        l[i, (i + 1) % m] = -1.0
        l[i, (i - 1) % m] = -1.0
    return l


def kronecker_sum(factors: list[np.ndarray]) -> np.ndarray:
    k = len(factors)
    dims = [f.shape[0] for f in factors]
    n = int(np.prod(dims))
    total = np.zeros((n, n), dtype=np.float64)
    for axis, fac in enumerate(factors):
        ops: list[np.ndarray] = []
        for j in range(k):
            ops.append(fac if j == axis else np.eye(dims[j], dtype=np.float64))
        term = ops[0]
        for op in ops[1:]:
            term = np.kron(term, op)
        total += term
    return total


def shift_permutation(dims: list[int], axis: int, delta: int) -> np.ndarray:
    n = int(np.prod(dims))
    p = np.zeros((n, n), dtype=np.float64)
    for flat in range(n):
        idx = list(unravel(flat, dims))
        idx[axis] = (idx[axis] + delta) % dims[axis]
        p[flat_index(dims, tuple(idx)), flat] = 1.0
    return p


def valuation_action(primes: list[int], mesh: int, exponents: list[int]) -> np.ndarray:
    dims = [mesh] * len(primes)
    acc = np.eye(int(np.prod(dims)), dtype=np.float64)
    for p, e, ax in zip(primes, exponents, range(len(primes))):
        if e:
            acc = shift_permutation(dims, ax, e % mesh) @ acc
    return acc


def s_unit_generators(primes: list[int]) -> list[tuple[int, ...]]:
    """Primitive S-unit relations p_i / p_j as exponent vectors."""
    if len(primes) < 2:
        return []
    gens: list[tuple[int, ...]] = []
    for i in range(1, len(primes)):
        v = [0] * len(primes)
        v[0] = 1
        v[i] = -1
        gens.append(tuple(v))
    return gens


def projector_trivial_character(generators: list[np.ndarray]) -> np.ndarray:
    """Average projector onto simultaneous +1 eigenspace of all generators."""
    if not generators:
        n = generators[0].shape[0] if generators else 1
        return np.eye(n)
    # P = average of (1/|G|) sum_g M(g) for abelian group — use Reynolds for cyclic gens
    p = np.eye(generators[0].shape[0], dtype=np.float64)
    for m in generators:
        # orbit average for cyclic permutation subgroup generated by m
        acc = np.zeros_like(m)
        cur = np.eye(m.shape[0], dtype=np.float64)
        used = set()
        for _ in range(m.shape[0] + 1):
            key = cur.tobytes()
            if key in used:
                break
            used.add(key)
            acc += cur
            cur = m @ cur
        acc /= len(used)
        p = acc @ p
    return p


def continuum_fourier_eigenvalue(primes: list[int], modes: tuple[int, ...]) -> float:
    return sum(
        (2.0 * math.pi * n / math.log(p)) ** 2
        for p, n in zip(primes, modes)
        if n != 0
    )


def discrete_fourier_eigenvalue(primes: list[int], mesh: int, modes: tuple[int, ...]) -> float:
    val = 0.0
    for p, n in zip(primes, modes):
        if n == 0:
            continue
        theta = 2.0 * math.pi * n / mesh
        val += 4.0 * math.sin(0.5 * theta) ** 2 * (mesh / math.log(p)) ** 2
    return val


def iter_fourier_modes(k: int, n_max: int) -> Iterator[tuple[int, ...]]:
    if k == 0:
        yield ()
        return
    for n in range(-n_max, n_max + 1):
        for rest in iter_fourier_modes(k - 1, n_max):
            yield (n,) + rest


def frequency_locked_modes(
    primes: list[int], omega: float, tol: float = 1e-6
) -> tuple[bool, dict[int, int]]:
    modes: dict[int, int] = {}
    for p in primes:
        lp = math.log(p)
        n = round(omega * lp / (2.0 * math.pi))
        if n == 0:
            return False, {}
        if abs(2.0 * math.pi * n / lp - omega) > tol:
            return False, {}
        modes[p] = n
    return True, modes


def scan_frequency_locked_spectrum(
    primes: list[int], n_omega: int, p0_index: int = 0
) -> list[dict]:
    if not primes:
        return []
    lp0 = math.log(primes[p0_index])
    out: list[dict] = []
    for k in range(1, n_omega + 1):
        omega = 2.0 * math.pi * k / lp0
        ok, modes = frequency_locked_modes(primes, omega)
        if ok:
            lam = continuum_fourier_eigenvalue(primes, tuple(modes[p] for p in primes))
            out.append({"omega": omega, "modes": modes, "lambda_sum": lam, "sqrt_lambda": math.sqrt(lam)})
    return out


def gamma_locked_candidates(primes: list[int], gammas: list[float]) -> list[dict]:
    out: list[dict] = []
    for g in gammas:
        modes: dict[int, int] = {}
        omegas: list[float] = []
        for p in primes:
            lp = math.log(p)
            n = max(1, round(g * lp / (2.0 * math.pi)))
            modes[p] = n
            omegas.append(2.0 * math.pi * n / lp)
        omega_mean = sum(omegas) / len(omegas)
        out.append(
            {
                "gamma": g,
                "omega_candidate": omega_mean,
                "gap": abs(omega_mean - g),
                "modes": modes,
            }
        )
    return out


def unconstrained_merged_omega(primes: list[int], n: int) -> list[float]:
    h: list[tuple[float, int, int]] = []
    for p in primes:
        heapq.heappush(h, (2.0 * math.pi / math.log(p), p, 1))
    omegas: list[float] = []
    while h and len(omegas) < n:
        om, p, k = heapq.heappop(h)
        omegas.append(om)
        heapq.heappush(h, (2.0 * math.pi * (k + 1) / math.log(p), p, k + 1))
    return omegas


def matrix_quotient_spectrum(primes: list[int], mesh: int) -> dict:
    """Product graph Laplacian + Reynolds projector for S-unit generators."""
    k = len(primes)
    dims = [mesh] * k
    l_factors = [cycle_laplacian(mesh) for _ in primes]
    l_full = kronecker_sum(l_factors)

    gens = s_unit_generators(primes)
    actions = [valuation_action(primes, mesh, list(g)) for g in gens]
    proj = projector_trivial_character(actions) if actions else np.eye(l_full.shape[0])

  # Restrict Laplacian to im(P): use eigenbasis of P with eigenvalue ~1
    w, v = np.linalg.eigh(proj)
    mask = w > 0.5
    basis = v[:, mask]
    if basis.shape[1] == 0:
        return {"mesh": mesh, "dim_invariant": 0, "eigenvalues": []}

    l_red = basis.T @ l_full @ basis
    evals = np.linalg.eigvalsh(l_red)
    evals = np.sort(np.real(evals))
    # continuum scale: multiply by (2*pi/mesh)^2 per axis rough correction
    scale = (2.0 * math.pi / mesh) ** 2
    omegas = [math.sqrt(max(e * scale, 0.0)) for e in evals if e > 1e-12][:40]
    return {
        "mesh": mesh,
        "n_primes": k,
        "dim_full": int(l_full.shape[0]),
        "dim_invariant": int(basis.shape[1]),
        "first_20_omega": omegas[:20],
        "note": "S-unit translation invariance alone; GL(1) frequency lock is stronger.",
    }


def compare_spectra(candidates: list[float], gammas: list[float], n: int) -> dict:
    m = min(len(candidates), len(gammas), n)
    if m == 0:
        return {"n_pairs": 0, "max_gap": None, "mean_gap": None}
    gaps = [abs(candidates[i] - gammas[i]) for i in range(m)]
    return {"n_pairs": m, "max_gap": max(gaps), "mean_gap": sum(gaps) / m, "gaps": gaps}


def build_report(
    primes: list[int],
    gammas: list[float],
    *,
    mesh: int,
    n_omega: int,
    n_compare: int,
) -> dict:
    uncon = unconstrained_merged_omega(primes, n_compare)
    locked_scan = scan_frequency_locked_spectrum(primes, n_omega)
    locked_omegas = [x["omega"] for x in locked_scan]
    gamma_locked = gamma_locked_candidates(primes, gammas[:n_compare])
    gamma_omegas = [x["omega_candidate"] for x in gamma_locked]
    matrix = matrix_quotient_spectrum(primes[: min(3, len(primes))], mesh)

    return {
        "phase": "5a_idele_class_laplacian",
        "primes": {"list": primes[:20], "count": len(primes), "p_max": primes[-1]},
        "mesh": mesh,
        "unconstrained_direct_sum": {
            "first_15_omega": uncon[:15],
            "vs_gamma": compare_spectra(uncon, gammas, n_compare),
        },
        "frequency_locked_scan": {
            "n_modes": len(locked_scan),
            "first_15": locked_scan[:15],
            "vs_gamma": compare_spectra(locked_omegas, gammas, min(n_compare, len(locked_omegas))),
        },
        "gamma_locked_nearest": {
            "first_10": gamma_locked[:10],
            "vs_gamma": compare_spectra(gamma_omegas, gammas, n_compare),
        },
        "matrix_s_unit_quotient": matrix,
        "verdict": _verdict(
            compare_spectra(uncon, gammas, n_compare),
            compare_spectra(gamma_omegas, gammas, n_compare),
            compare_spectra(locked_omegas, gammas, min(n_compare, len(locked_omegas))),
        ),
    }


def _verdict(uncon: dict, locked: dict, locked_scan: dict) -> dict:
    return {
        "unconstrained_spectral_fail": (uncon.get("max_gap") or 0) > 5.0,
        "frequency_locked_improves": (locked.get("max_gap") or 1e9) < (uncon.get("max_gap") or 0),
        "locked_max_gap": locked.get("max_gap"),
        "locked_scan_max_gap": locked_scan.get("max_gap"),
        "uncon_max_gap": uncon.get("max_gap"),
        "interpretation": (
            "Direct sum fails Tier-4b; GL(1) frequency-locked quotient moves spectrum "
            "onto the gamma scale. Full idele-class Laplacian requires the adelic measure quotient."
        ),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--primes", type=int, default=5, help="number of primes in S")
    ap.add_argument("--prime-limit", type=int, default=200)
    ap.add_argument("--mesh", type=int, default=12)
    ap.add_argument("--n-omega", type=int, default=800)
    ap.add_argument("--n-compare", type=int, default=30)
    ap.add_argument("--n-zeros", type=int, default=50)
    ap.add_argument("--output", default=str(TRACES / "idele_class_spectrum.json"))
    args = ap.parse_args()

    all_primes = sieve(args.prime_limit)
    primes = all_primes[: args.primes]
    gammas = load_zeros(args.n_zeros)

    report = build_report(
        primes, gammas, mesh=args.mesh, n_omega=args.n_omega, n_compare=args.n_compare
    )

    out = Path(args.output)
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"Wrote {out}")
    v = report["verdict"]
    print(f"uncon max_gap={v['uncon_max_gap']:.4f}  locked max_gap={v['locked_max_gap']:.4f}")
    print(f"frequency_locked_improves={v['frequency_locked_improves']}")


if __name__ == "__main__":
    main()
