#include "AnaLeanCodegenValidation.hxx"
#include "MrsProofGate.hxx"

#include <cmath>
#include <sstream>

namespace Marshal::AnaVM {
namespace {

bool contains(const std::string& body, const std::string& needle) {
    return body.find(needle) != std::string::npos;
}

void require_contains(LeanCodegenValidationReport& r, const std::string& body,
                      const std::string& needle, const char* role, const char* msg) {
    if (!contains(body, needle)) {
        std::ostringstream oss;
        oss << msg << " (missing `" << needle << "`)";
        r.fail(role, oss.str());
    }
}

void forbid_pattern(LeanCodegenValidationReport& r, const std::string& body,
                    const std::string& pattern, const char* role, const char* msg) {
    if (contains(body, pattern)) r.fail(role, msg);
}

}  // namespace

void LeanCodegenValidationReport::fail(const std::string& role, const std::string& message) {
    ok = false;
    issues.push_back({role, message});
}

LeanCodegenValidationReport validate_xi_hadamard_cert_lean(const std::string& body,
                                                           const Heat::XiHadamardReport& report) {
    LeanCodegenValidationReport r;
    constexpr const char* role = "cert";
    require_contains(r, body, "AUTO-GENERATED by AnaVM AnaLeanEmitter", role, "cert header");
    require_contains(r, body, "namespace HPAnalysis", role, "cert namespace");
    require_contains(r, body, "import Analysis.CertifiedBounds", role, "cert import");
    require_contains(r, body, "import Mathlib.Tactic", role, "mathlib tactic");
    require_contains(r, body, "pinnedAnaVmXiHadamardGridCount", role, "grid count pin");
    require_contains(r, body, "pinnedAnaVmXiHadamardProofChainClosed", role, "proof chain pin");
    require_contains(r, body, "pinnedAnaVmHolomorphyMaxUniformGap", role, "holomorphy gap pin");
    require_contains(r, body, "pinnedAnaVmXiHadamardMaxGridRelGap_bounded", role, "grid rel bound");
    require_contains(r, body, "pinnedAnaVmHolomorphyMaxUniformGap_bounded", role, "holo bound");
    require_contains(r, body, "theorem pinnedAnaVm_xi_hadamard_audit_bounds_ok", role, "audit agg");
    require_contains(r, body, "theorem pinnedAnaVm_holomorphy_audit_bounds_ok", role, "holo audit");
    require_contains(r, body, "theorem pinnedAnaVmGenusOneLogHeadMajorant_ge_ratio_envelope", role,
                     "genus head envelope");
    require_contains(r, body, "pinnedAnaVmGenusOneLogCapDominantLogUb", role,
                     "genus head dominant log ub");
    require_contains(r, body, "theorem pinnedAnaVmGenusOneLogMaxHeadEnvelope_lt_majorant", role,
                     "genus head majorant margin");
    require_contains(r, body, "pinnedAnaVmGenusOneLogCapRatio_le_majorant", role,
                     "head envelope cap cite");
    require_contains(r, body, "Real.log_le_log", role, "head envelope log monotonicity");
    require_contains(r, body, "norm_num", role, "norm_num tactic");
    require_contains(r, body, "Real.log_le_iff_le_exp", role, "head envelope log/exp cert");
    forbid_pattern(r, body, "≤ 130", role, "forbidden coarse head bound shortcut");
    forbid_pattern(r, body, "suffices h :", role, "forbidden suffices coarse bound");
    forbid_pattern(r, body, "change _ ≤ (10000", role, "forbidden change coarse bound");
    if (!genus_one_head_envelope_cert_proof_ok(body))
        r.fail(role, "head envelope proof must use audit cap ratio + majorant margin");
    forbid_pattern(r, body, "sorry", role, "cert must not contain sorry");
    forbid_pattern(r, body, "admit", role, "cert must not contain admit");
    forbid_pattern(r, body, ":= True", role, "cert must not hardcode True");
    if (report.proof_chain_closed && !xi_hadamard_report_bounds_ok(report))
        r.fail(role, "report bounds exceed tolerance while proof_chain_closed=true");
    return r;
}

LeanCodegenValidationReport validate_xi_hadamard_canonical_lean(const std::string& body) {
    LeanCodegenValidationReport r;
    constexpr const char* role = "canonical";
    require_contains(r, body, "AUTO-GENERATED by AnaVM AnaLeanEmitter", role, "canonical header");
    require_contains(r, body, "import Analysis.MarshalXiHadamardAnaVmCert", role, "cert import");
    require_contains(r, body, "import Analysis.MarshalWedgeCert", role, "wedge cert import");
    require_contains(r, body, "theorem marshalAnaVm_xi_hadamard_audit_ok", role, "audit bridge");
    require_contains(r, body, "theorem marshalAnaVm_genus_one_log_summability", role, "genus bridge");
    require_contains(r, body, "marshal_genus_one_log_summability_closed", role, "genus spine");
    require_contains(r, body, "theorem marshalAnaVm_off_height_log_summability", role, "off-height");
    forbid_pattern(r, body, "sorry", role, "canonical must not contain sorry");
    forbid_pattern(r, body, ":= True", role, "canonical must not hardcode True");
    return r;
}

LeanCodegenValidationReport validate_xi_hadamard_rh_closure_lean(const std::string& body) {
    LeanCodegenValidationReport r;
    constexpr const char* role = "rh_closure";
    require_contains(r, body, "AUTO-GENERATED by AnaVM AnaLeanEmitter", role, "rh header");
    require_contains(r, body, "import Analysis.MarshalHadamardWeierstrassClosure", role, "closure import");
    require_contains(r, body, "import Analysis.MarshalInfiniteDetHolomorphy", role, "holomorphy import");
    require_contains(r, body, "theorem marshalAnaVm_holomorphy_proved", role, "holomorphy bridge");
    require_contains(r, body, "theorem marshalAnaVm_wedge_grid_spectral_eq_riemannXi", role, "grid spectral");
    require_contains(r, body, "theorem marshal_mrs_weierstrass_identification", role, "MRS weierstrass");
    require_contains(r, body, "theorem classical_rh_unconditional_mrs", role, "MRS RH capstone");
    require_contains(r, body, "import Analysis.MarshalAnaVmAnalyticClosure", role, "analytic closure import");
    forbid_pattern(r, body, "sorry", role, "rh_closure must not contain sorry");
    forbid_pattern(r, body, ":= True", role, "rh_closure must not hardcode True");
    if (contains(body, "classical_riemann_hypothesis_marshal_proved") &&
        contains(body, "(hEnt : MarshalHadamardEntireRatioData)")) {
        r.fail(role, "rh_closure must not retain parameterized Marshal RH capstone");
    }
    return r;
}

bool rh_closure_lean_is_parameterless(const std::string& body) {
    if (!contains(body, "theorem classical_rh_unconditional_mrs")) return false;
    if (!contains(body, "theorem classical_riemann_hypothesis_marshal_proved")) return false;
    return !contains(body, "(hEnt : MarshalHadamardEntireRatioData)");
}

bool genus_one_head_envelope_cert_proof_ok(const std::string& body) {
    return contains(body, "pinnedAnaVmGenusOneLogHeadMajorant_ge_ratio_envelope") &&
           contains(body, "pinnedAnaVmGenusOneLogCapRatio_le_majorant") &&
           contains(body, "pinnedAnaVmGenusOneLogCapDominantLogUb") &&
           contains(body, "have hmono") &&
           contains(body, "exact le_trans hmono pinnedAnaVmGenusOneLogCapRatio_le_majorant") &&
           !contains(body, "≤ 130");
}

LeanCodegenValidationReport validate_genus_one_log_analytic_bridge_lean(const std::string& body) {
    LeanCodegenValidationReport r;
    constexpr const char* role = "genus_analytic_bridge";
    require_contains(r, body, "AUTO-GENERATED by AnaVM AnaLeanEmitter", role, "bridge header");
    require_contains(r, body, "weierstrass_log_rest_large_norm_le_head_envelope", role, "large-z bound");
    require_contains(r, body, "weierstrass_log_norm_le_head_envelope_ratio", role, "ratio envelope");
    require_contains(r, body, "(2 : ℝ) ≤ ‖z‖", role, "large-z norm threshold");
    require_contains(r, body, "norm_sub_log_sub_one_le_at_R", role, "large-z log core");
    forbid_pattern(r, body, "sorry", role, "bridge must not contain sorry");
    forbid_pattern(r, body, "≤ 130", role, "forbidden coarse bound");
    return r;
}

LeanCodegenValidationReport validate_marshal_genus_one_log_bounds_lean(const std::string& body) {
    LeanCodegenValidationReport r;
    constexpr const char* role = "genus_bounds";
    require_contains(r, body, "AUTO-GENERATED by AnaVM AnaLeanEmitter", role, "bounds header");
    require_contains(r, body, "import Analysis.MarshalGenusOneLogAnalyticBridge", role, "bridge import");
    require_contains(r, body, "marshal_log_factor_norm_le_coarse_on_closedBall", role, "head majorant");
    require_contains(r, body, "weierstrass_log_norm_le_head_envelope_ratio", role, "ratio wire");
    forbid_pattern(r, body, "sorry", role, "bounds must not contain sorry");
    return r;
}

LeanCodegenValidationReport validate_xi_hadamard_lean_bundle(
    const std::string& cert_body, const std::string& canonical_body,
    const std::string& rh_body, const std::string& genus_bridge_body,
    const std::string& genus_bounds_body, const Heat::XiHadamardReport& report) {
    auto cert = validate_xi_hadamard_cert_lean(cert_body, report);
    auto canon = validate_xi_hadamard_canonical_lean(canonical_body);
    auto rh = validate_xi_hadamard_rh_closure_lean(rh_body);
    auto bridge = validate_genus_one_log_analytic_bridge_lean(genus_bridge_body);
    auto bounds = validate_marshal_genus_one_log_bounds_lean(genus_bounds_body);
    LeanCodegenValidationReport out;
    out.ok = cert.ok && canon.ok && rh.ok && bridge.ok && bounds.ok;
    out.issues.reserve(cert.issues.size() + canon.issues.size() + rh.issues.size() +
                       bridge.issues.size() + bounds.issues.size());
    for (const auto& i : cert.issues) out.issues.push_back(i);
    for (const auto& i : canon.issues) out.issues.push_back(i);
    for (const auto& i : rh.issues) out.issues.push_back(i);
    for (const auto& i : bridge.issues) out.issues.push_back(i);
    for (const auto& i : bounds.issues) out.issues.push_back(i);
    return out;
}

LeanCodegenValidationReport validate_xi_hadamard_lean_bundle(
    const std::string& cert_body, const std::string& canonical_body,
    const std::string& rh_body, const Heat::XiHadamardReport& report) {
    return validate_xi_hadamard_lean_bundle(cert_body, canonical_body, rh_body, "", "", report);
}

}  // namespace Marshal::AnaVM
