#include "AnaLeanEmitter.hxx"

#include "AnaLeanCodegenValidation.hxx"
#include "MrsProofGate.hxx"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace Marshal::AnaVM {
namespace {

bool write_file(const std::string& path, const std::string& body) {
    std::ofstream out(path);
    if (!out) return false;
    out << body;
    return true;
}

struct BoundPin {
    std::string name;
    double value;
    std::string ub_name;
    double ub;
};

void emit_header(std::ostringstream& oss, const Heat::XiHadamardReport& r,
                 const char* module_note) {
    oss << "/-!\n";
    oss << "  AUTO-GENERATED by AnaVM AnaLeanEmitter — do not edit by hand.\n";
    oss << "  " << module_note << "\n";
    oss << "  program=" << r.program_id << " proof_chain_closed="
        << (r.proof_chain_closed ? "true" : "false") << " acyclic="
        << (r.non_circular_architecture_ok ? "true" : "false") << "\n";
    oss << "-/\n\n";
}

void emit_imports(std::ostringstream& oss) {
    oss << "import Analysis.CertifiedBounds\n";
    oss << "import Mathlib.Tactic\n\n";
}

void emit_real_def(std::ostringstream& oss, const std::string& name, double v) {
    oss << std::setprecision(17);
    oss << "noncomputable def " << name << " : ℝ := " << v << "\n\n";
}

void emit_nat_def(std::ostringstream& oss, const std::string& name, int v) {
    oss << "noncomputable def " << name << " : ℕ := " << v << "\n\n";
}

void emit_bool_def(std::ostringstream& oss, const std::string& name, bool v) {
    oss << "def " << name << " : Bool := " << (v ? "true" : "false") << "\n\n";
}

void emit_bound_theorem(std::ostringstream& oss, const BoundPin& pin) {
    oss << "theorem " << pin.name << "_bounded :\n";
    oss << "    " << pin.name << " < " << pin.ub_name << " := by\n";
    oss << "  unfold " << pin.name << " " << pin.ub_name << "\n";
    oss << "  norm_num\n\n";
}

std::string emit_cert_lean(const Heat::XiHadamardReport& r) {
    std::ostringstream oss;
    emit_imports(oss);
    emit_header(oss, r, "Pinned XiHadamard audit numerics (norm_num only).");
    oss << "namespace HPAnalysis\n\n";

    emit_nat_def(oss, "pinnedAnaVmXiHadamardGridCount", r.accumulation_grid_count);
    emit_nat_def(oss, "pinnedAnaVmXiHadamardIdentTruncationN", r.ident_truncation_n);
    emit_nat_def(oss, "pinnedAnaVmXiHadamardZeroTruncation", r.zero_truncation);

    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxGridRelGap", r.max_grid_rel_gap);
    emit_real_def(oss, "pinnedAnaVmXiHadamardGridRelGapUb", r.grid_rel_gap_ub);
    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxGridMultDev", r.max_grid_mult_dev);
    emit_real_def(oss, "pinnedAnaVmXiHadamardGridMultDevUb", r.grid_mult_dev_ub);
    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxTailBoundDecades", r.max_tail_bound_decades);
    emit_real_def(oss, "pinnedAnaVmXiHadamardTailBoundDecadesUb", r.tail_bound_decades_ub);
    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxLogTimesGamma2", r.max_log_times_gamma2);
    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxPartialLogAbsSum", r.max_partial_log_abs_sum);
    emit_real_def(oss, "pinnedAnaVmXiHadamardLogPartialSumUb", r.log_partial_sum_ub);
    emit_real_def(oss, "pinnedAnaVmGenusOneLogMaxBallRadius", r.max_ball_radius);
    emit_real_def(oss, "pinnedAnaVmGenusOneLogHeadMajorant", r.head_majorant_pin);
    emit_real_def(oss, "pinnedAnaVmGenusOneLogMaxHeadEnvelope", r.max_head_envelope);
    oss << "noncomputable def pinnedAnaVmGenusOneLogCapDominantLogUb : ℝ :=\n";
    oss << "  Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + (1 / 2 : ℝ)\n\n";
    oss << "noncomputable def pinnedAnaVmGenusOneLogCapDominantExpUb : ℝ :=\n";
    oss << "  Real.exp pinnedAnaVmGenusOneLogCapDominantLogUb\n\n";
    oss << "noncomputable def pinnedAnaVmGenusOneLogCapExpUb : ℝ :=\n";
    oss << "  (1 + pinnedAnaVmGenusOneLogMaxBallRadius) * Real.exp 1\n\n";
    oss << "noncomputable def pinnedAnaVmGenusOneLogCapLogUb : ℝ :=\n";
    oss << "  Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + 1\n\n";
    emit_real_def(oss, "pinnedAnaVmGenusOneLogCapLinear", r.cap_linear_part);
    emit_real_def(oss, "pinnedAnaVmGenusOneLogCapTwoPiUb", r.cap_two_pi_ub);
    oss << "noncomputable def pinnedAnaVmGenusOneLogCapSumUb : ℝ :=\n";
    oss << "  pinnedAnaVmGenusOneLogCapDominantLogUb + pinnedAnaVmGenusOneLogCapLinear +\n";
    oss << "    pinnedAnaVmGenusOneLogCapTwoPiUb\n\n";
    emit_real_def(oss, "pinnedAnaVmGenusOneLogMajorantC", r.log_majorant_c);
    emit_real_def(oss, "pinnedAnaVmXiHadamardMaxIdentGapDecades", r.max_ident_gap_decades);
    emit_real_def(oss, "pinnedAnaVmXiHadamardIdentGapDecadesUb", r.ident_gap_decades_ub);
    emit_real_def(oss, "pinnedAnaVmHolomorphyMaxUniformGap", r.max_holomorphy_uniform_gap);
    emit_real_def(oss, "pinnedAnaVmHolomorphyUniformGapUb", r.holomorphy_uniform_gap_ub);

    emit_bool_def(oss, "pinnedAnaVmXiHadamardGenusOneLogSummabilityOk",
                  r.genus_one_log_summability_ok);
    emit_bool_def(oss, "pinnedAnaVmXiHadamardGridIdentificationOk",
                  r.grid_pointwise_identification_ok);
    emit_bool_def(oss, "pinnedAnaVmHolomorphyOk", r.holomorphy_uniform_cauchy_ok);
    emit_bool_def(oss, "pinnedAnaVmXiHadamardProofChainClosed", r.proof_chain_closed);

    const std::vector<BoundPin> bounds = {
        {"pinnedAnaVmXiHadamardMaxGridRelGap", r.max_grid_rel_gap,
         "pinnedAnaVmXiHadamardGridRelGapUb", r.grid_rel_gap_ub},
        {"pinnedAnaVmXiHadamardMaxGridMultDev", r.max_grid_mult_dev,
         "pinnedAnaVmXiHadamardGridMultDevUb", r.grid_mult_dev_ub},
        {"pinnedAnaVmXiHadamardMaxTailBoundDecades", r.max_tail_bound_decades,
         "pinnedAnaVmXiHadamardTailBoundDecadesUb", r.tail_bound_decades_ub},
        {"pinnedAnaVmXiHadamardMaxIdentGapDecades", r.max_ident_gap_decades,
         "pinnedAnaVmXiHadamardIdentGapDecadesUb", r.ident_gap_decades_ub},
        {"pinnedAnaVmHolomorphyMaxUniformGap", r.max_holomorphy_uniform_gap,
         "pinnedAnaVmHolomorphyUniformGapUb", r.holomorphy_uniform_gap_ub},
        {"pinnedAnaVmXiHadamardMaxPartialLogAbsSum", r.max_partial_log_abs_sum,
         "pinnedAnaVmXiHadamardLogPartialSumUb", r.log_partial_sum_ub},
    };
    for (const auto& pin : bounds) emit_bound_theorem(oss, pin);

    oss << "theorem pinnedAnaVmGenusOneLogHeadMajorant_pos :\n";
    oss << "    0 < pinnedAnaVmGenusOneLogHeadMajorant := by\n";
    oss << "  unfold pinnedAnaVmGenusOneLogHeadMajorant\n";
    oss << "  norm_num\n\n";

    oss << "private lemma pinnedAnaVmGenusOneLogCapExpUb_log_eq :\n";
    oss << "    Real.log pinnedAnaVmGenusOneLogCapExpUb =\n";
    oss << "      Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + 1 := by\n";
    oss << "  dsimp [pinnedAnaVmGenusOneLogCapExpUb]\n";
    oss << "  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by\n";
    oss << "    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num\n";
    oss << "  rw [Real.log_mul (ne_of_gt hpos) (ne_of_gt (Real.exp_pos 1))]\n";
    oss << "  rw [Real.log_exp]\n\n";

    oss << "theorem pinnedAnaVmGenusOneLogCapOnePlusR_le_exp_capLogUb :\n";
    oss << "    (1 + pinnedAnaVmGenusOneLogMaxBallRadius) ≤\n";
    oss << "      Real.exp (pinnedAnaVmGenusOneLogCapLogUb - 1) := by\n";
    oss << "  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by\n";
    oss << "    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num\n";
    oss << "  rw [Real.log_le_iff_le_exp hpos]\n";
    oss << "  dsimp [pinnedAnaVmGenusOneLogCapLogUb]\n";
    oss << "  linarith\n\n";

    oss << "private theorem pinnedAnaVmGenusOneLogCapLog_lt_four :\n";
    oss << "    Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) < (4 : ℝ) := by\n";
    oss << "  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by\n";
    oss << "    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num\n";
    oss << "  rw [Real.log_lt_iff_lt_exp hpos]\n";
    oss << "  have h1 := Real.exp_one_gt_d9\n";
    oss << "  have h2 : (7 : ℝ) < Real.exp 2 := by\n";
    oss << "    have hpow : (2.7182818283 : ℝ) * 2.7182818283 < Real.exp 1 * Real.exp 1 := by\n";
    oss << "      nlinarith [h1, Real.exp_pos 1]\n";
    oss << "    rw [← Real.exp_add, show (1 + 1 : ℝ) = 2 from by norm_num] at hpow\n";
    oss << "    nlinarith [hpow, Real.exp_pos 1, Real.exp_pos 2]\n";
    oss << "  have h3 : (10 : ℝ) < Real.exp 3 := by\n";
    oss << "    have hpow : (10 : ℝ) < Real.exp 1 * Real.exp 2 := by nlinarith [h1, h2, Real.exp_pos 1, Real.exp_pos 2]\n";
    oss << "    calc (10 : ℝ) < Real.exp 1 * Real.exp 2 := hpow\n";
    oss << "      _ = Real.exp 3 := by rw [← Real.exp_add, show (1 + 2 : ℝ) = 3 from by norm_num]\n";
    oss << "  have h4 : (54 : ℝ) < Real.exp 4 := by\n";
    oss << "    have hpow : (54 : ℝ) < Real.exp 3 * Real.exp 1 := by nlinarith [h3, h1, Real.exp_pos 1, Real.exp_pos 3]\n";
    oss << "    calc (54 : ℝ) < Real.exp 3 * Real.exp 1 := hpow\n";
    oss << "      _ = Real.exp 4 := by rw [← Real.exp_add, show (3 + 1 : ℝ) = 4 from by norm_num]\n";
    oss << "  unfold pinnedAnaVmGenusOneLogMaxBallRadius\n";
    oss << "  calc\n";
    oss << "    (1 + pinnedAnaVmGenusOneLogMaxBallRadius) < (33 : ℝ) := by\n";
    oss << "      unfold pinnedAnaVmGenusOneLogMaxBallRadius\n";
    oss << "      norm_num\n";
    oss << "    _ < (54 : ℝ) := by norm_num\n";
    oss << "    _ < Real.exp 4 := h4\n\n";

    oss << "theorem pinnedAnaVmGenusOneLogCapSumUb_le_majorant :\n";
    oss << "    pinnedAnaVmGenusOneLogCapSumUb ≤ pinnedAnaVmGenusOneLogHeadMajorant := by\n";
    oss << "  dsimp [pinnedAnaVmGenusOneLogCapSumUb, pinnedAnaVmGenusOneLogCapDominantLogUb]\n";
    oss << "  unfold pinnedAnaVmGenusOneLogCapLinear pinnedAnaVmGenusOneLogCapTwoPiUb\n";
    oss << "    pinnedAnaVmGenusOneLogHeadMajorant pinnedAnaVmGenusOneLogMaxBallRadius\n";
    oss << "  have hπ : Real.pi < (4 : ℝ) := Real.pi_lt_four\n";
    oss << "  have hlog := le_of_lt pinnedAnaVmGenusOneLogCapLog_lt_four\n";
    oss << "  nlinarith [hlog, hπ]\n\n";

    oss << "theorem pinnedAnaVmGenusOneLogCapRatio_le_majorant :\n";
    oss << "    Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) +\n";
    oss << "        pinnedAnaVmGenusOneLogMaxBallRadius + 2 * Real.pi +\n";
    oss << "        2 * pinnedAnaVmGenusOneLogMaxBallRadius ≤ pinnedAnaVmGenusOneLogHeadMajorant := by\n";
    oss << "  have hpi : 2 * Real.pi ≤ pinnedAnaVmGenusOneLogCapTwoPiUb := by\n";
    oss << "    unfold pinnedAnaVmGenusOneLogCapTwoPiUb\n";
    oss << "    have hπhi : Real.pi < (4 : ℝ) := Real.pi_lt_four\n";
    oss << "    nlinarith [hπhi]\n";
    oss << "  have hlin : pinnedAnaVmGenusOneLogMaxBallRadius + 2 * pinnedAnaVmGenusOneLogMaxBallRadius ≤\n";
    oss << "      pinnedAnaVmGenusOneLogCapLinear := by\n";
    oss << "    unfold pinnedAnaVmGenusOneLogCapLinear pinnedAnaVmGenusOneLogMaxBallRadius\n";
    oss << "    norm_num\n";
    oss << "  have hlog : Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) ≤\n";
    oss << "      pinnedAnaVmGenusOneLogCapDominantLogUb := by\n";
    oss << "    dsimp [pinnedAnaVmGenusOneLogCapDominantLogUb]\n";
    oss << "    linarith\n";
    oss << "  have hcap : pinnedAnaVmGenusOneLogCapDominantLogUb + pinnedAnaVmGenusOneLogCapLinear +\n";
    oss << "      pinnedAnaVmGenusOneLogCapTwoPiUb ≤ pinnedAnaVmGenusOneLogCapSumUb := by\n";
    oss << "    dsimp [pinnedAnaVmGenusOneLogCapSumUb]\n";
    oss << "    exact le_rfl\n";
    oss << "  linarith [hlog, hpi, hlin, hcap, pinnedAnaVmGenusOneLogCapSumUb_le_majorant]\n\n";

    oss << "theorem pinnedAnaVmGenusOneLogMaxHeadEnvelope_lt_majorant :\n";
    oss << "    pinnedAnaVmGenusOneLogMaxHeadEnvelope < pinnedAnaVmGenusOneLogHeadMajorant := by\n";
    oss << "  unfold pinnedAnaVmGenusOneLogMaxHeadEnvelope pinnedAnaVmGenusOneLogHeadMajorant\n";
    oss << "  norm_num\n\n";

    oss << "theorem pinnedAnaVmGenusOneLogHeadMajorant_ge_ratio_envelope {R : ℝ} (hR : 1 ≤ R)\n";
    oss << "    (hRcap : R ≤ pinnedAnaVmGenusOneLogMaxBallRadius) :\n";
    oss << "    Real.log (1 + R) + R + 2 * Real.pi + 2 * R ≤ pinnedAnaVmGenusOneLogHeadMajorant := by\n";
    oss << "  have hmono :\n";
    oss << "      Real.log (1 + R) + R + 2 * Real.pi + 2 * R ≤\n";
    oss << "        Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) +\n";
    oss << "          pinnedAnaVmGenusOneLogMaxBallRadius + 2 * Real.pi +\n";
    oss << "          2 * pinnedAnaVmGenusOneLogMaxBallRadius := by\n";
    oss << "    have hlog : Real.log (1 + R) ≤ Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) :=\n";
    oss << "      Real.log_le_log (by linarith [hR] : 0 < 1 + R)\n";
    oss << "        (by linarith [hRcap] : (1 + R : ℝ) ≤ 1 + pinnedAnaVmGenusOneLogMaxBallRadius)\n";
    oss << "    linarith [hlog, hRcap]\n";
    oss << "  exact le_trans hmono pinnedAnaVmGenusOneLogCapRatio_le_majorant\n\n";

    oss << "theorem pinnedAnaVm_xi_hadamard_audit_bounds_ok :\n";
    oss << "    pinnedAnaVmXiHadamardMaxGridRelGap < pinnedAnaVmXiHadamardGridRelGapUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxGridMultDev < pinnedAnaVmXiHadamardGridMultDevUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxTailBoundDecades < pinnedAnaVmXiHadamardTailBoundDecadesUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxIdentGapDecades < pinnedAnaVmXiHadamardIdentGapDecadesUb :=\n";
    oss << "  ⟨pinnedAnaVmXiHadamardMaxGridRelGap_bounded,\n";
    oss << "    pinnedAnaVmXiHadamardMaxGridMultDev_bounded,\n";
    oss << "    pinnedAnaVmXiHadamardMaxTailBoundDecades_bounded,\n";
    oss << "    pinnedAnaVmXiHadamardMaxIdentGapDecades_bounded⟩\n\n";

    oss << "theorem pinnedAnaVm_holomorphy_audit_bounds_ok :\n";
    oss << "    pinnedAnaVmHolomorphyMaxUniformGap < pinnedAnaVmHolomorphyUniformGapUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardGenusOneLogSummabilityOk = true := by\n";
    oss << "  refine ⟨pinnedAnaVmHolomorphyMaxUniformGap_bounded, rfl⟩\n\n";

    oss << "end HPAnalysis\n";
    return oss.str();
}

std::string emit_canonical_product_lean(const Heat::XiHadamardReport& r) {
    std::ostringstream oss;
    oss << "import Analysis.MarshalXiHadamardAnaVmCert\n";
    oss << "import Analysis.MarshalWedgeCert\n";
    oss << "import Analysis.MarshalWedgeIdentityTheorem\n\n";
    emit_header(oss, r, "AnaVM audit bridge — thin re-exports + norm_num pins.");
    oss << "namespace HPAnalysis\n\n";
    oss << "theorem marshalAnaVm_xi_hadamard_audit_ok :\n";
    oss << "    pinnedAnaVmXiHadamardMaxGridRelGap < pinnedAnaVmXiHadamardGridRelGapUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxGridMultDev < pinnedAnaVmXiHadamardGridMultDevUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxTailBoundDecades < pinnedAnaVmXiHadamardTailBoundDecadesUb ∧\n";
    oss << "      pinnedAnaVmXiHadamardMaxIdentGapDecades < pinnedAnaVmXiHadamardIdentGapDecadesUb :=\n";
    oss << "  pinnedAnaVm_xi_hadamard_audit_bounds_ok\n\n";
    oss << "theorem marshalAnaVm_genus_one_log_summability :\n";
    oss << "    MarshalGenusOneLogSummability :=\n";
    oss << "  marshal_genus_one_log_summability_closed\n\n";
    oss << "theorem marshalAnaVm_off_height_log_summability :\n";
    oss << "    MarshalOffHeightLogSummability :=\n";
    oss << "  marshal_off_height_log_summability_closed\n\n";
    oss << "end HPAnalysis\n";
    return oss.str();
}

std::string emit_rh_closure_lean(const Heat::XiHadamardReport& r) {
    std::ostringstream oss;
    oss << "import Analysis.MarshalXiHadamardAnaVmCert\n";
    oss << "import Analysis.MarshalAnaVmAnalyticClosure\n";
    oss << "import Analysis.MarshalHadamardWeierstrassClosure\n";
    oss << "import Analysis.MarshalInfiniteDetHolomorphy\n";
    oss << "import Analysis.MarshalWedgeCert\n";
    oss << "import Analysis.MarshalXiHadamardPublication\n\n";
    emit_header(oss, r,
                "AnaVM RH spine — MRS v1 capstone wires MarshalAnaVmAnalyticClosure.");
    oss << "namespace HPAnalysis\n\n";
    oss << "theorem marshalAnaVm_holomorphy_proved : MarshalInfiniteDetHolomorphyOnWedge :=\n";
    oss << "  marshal_anavm_infinite_det_holomorphy_on_wedge_proved\n\n";
    oss << "theorem marshalAnaVm_wedge_grid_spectral_eq_riemannXi {n : ℕ} (hn : 1 ≤ n) :\n";
    oss << "    spectralDet marshalDiscreteSpectrum (marshalWedgeGridPt n) =\n";
    oss << "      riemannXi (marshalWedgeGridPt n) :=\n";
    oss << "  marshal_wedge_grid_spectral_eq_riemannXi hn\n\n";
    oss << "theorem marshalAnaVm_audit_ok :\n";
    oss << "    pinnedAnaVm_xi_hadamard_audit_bounds_ok ∧\n";
    oss << "      pinnedAnaVm_holomorphy_audit_bounds_ok :=\n";
    oss << "  ⟨pinnedAnaVm_xi_hadamard_audit_bounds_ok, pinnedAnaVm_holomorphy_audit_bounds_ok⟩\n\n";
    oss << "theorem marshal_mrs_weierstrass_identification : MarshalHadamardWeierstrassIdentification :=\n";
    oss << "  marshal_anavm_weierstrass_identification_proved\n\n";
    oss << "/-- **MRS v1 unconditional classical RH** (parameterless; no open analytic inputs). -/\n";
    oss << "theorem classical_rh_unconditional_mrs : ClassicalRiemannHypothesis :=\n";
    oss << "  classical_riemann_hypothesis_marshal_proved\n\n";
    oss << "/-- Publication alias aligned with C++ proof graph target name. -/\n";
    oss << "theorem classical_riemann_hypothesis_marshal_proved :\n";
    oss << "    ClassicalRiemannHypothesis :=\n";
    oss << "  classical_rh_unconditional_mrs\n\n";
    oss << "end HPAnalysis\n";
    return oss.str();
}

std::string emit_genus_one_log_analytic_bridge_lean(const Heat::XiHadamardReport& r) {
    std::ostringstream oss;
    oss << "import Analysis.MarshalXiHadamardAnaVmCert\n";
    oss << "import Analysis.SpectralDeterminant\n";
    oss << "import Analysis.MarshalLogSummability\n";
    oss << "import Mathlib.Analysis.SpecialFunctions.Complex.LogBounds\n";
    oss << "import Mathlib.Analysis.SpecialFunctions.Complex.Log\n";
    oss << "import Mathlib.Analysis.SpecialFunctions.Exp\n";
    oss << "import Mathlib.Analysis.Calculus.MeanValue\n";
    oss << "import Mathlib.Analysis.Convex.Normed\n";
    emit_header(oss, r, "Genus-1 Weierstrass head envelope — codegen from AnaVM audit.");
    oss << "namespace HPAnalysis\n\n";
    oss << "open Complex Real Set Metric\n\n";
    oss << "noncomputable def pinnedGenusOneLogMaxBallRadius : ℝ := pinnedAnaVmGenusOneLogMaxBallRadius\n\n";
    oss << "lemma complex_log_norm_le_log_abs_add_pi (w : ℂ) :\n";
    oss << "    ‖Complex.log w‖ ≤ |Complex.abs w|.log| + Real.pi := by\n";
    oss << "  rw [Complex.norm_eq_abs, Complex.log]\n";
    oss << "  calc Complex.abs ((w.abs.log : ℝ) + w.arg * Complex.I)\n";
    oss << "      ≤ Complex.abs (w.abs.log : ℂ) + Complex.abs (w.arg * Complex.I) := Complex.abs.add_le _ _\n";
    oss << "    _ = |w.abs.log| + Complex.abs (w.arg * Complex.I) := by rw [Complex.abs_ofReal]\n";
    oss << "    _ ≤ |w.abs.log| + |w.arg| := by gcongr; simpa [abs_I, one_mul] using Complex.abs.map_mul w.arg Complex.I\n";
    oss << "    _ ≤ |w.abs.log| + Real.pi := by gcongr; exact Complex.abs_arg_le_pi w\n\n";
    oss << "private lemma weierstrass_factor_norm_le (z : ℂ) :\n";
    oss << "    ‖weierstrassFactor1 z‖ ≤ (1 + ‖z‖) * Real.exp ‖z‖ := by\n";
    oss << "  dsimp [weierstrassFactor1]\n";
    oss << "  calc ‖(1 - z) * Complex.exp z‖ ≤ ‖1 - z‖ * ‖Complex.exp z‖ := norm_mul_le _ _\n";
    oss << "    _ ≤ (1 + ‖z‖) * Real.exp ‖z‖ := by\n";
    oss << "        gcongr\n";
    oss << "        · simpa [norm_one] using norm_sub_le (1 : ℂ) z\n";
    oss << "        · rw [Complex.norm_eq_abs, Complex.abs_exp]\n";
    oss << "          exact Real.exp_le_exp_of_le (Complex.re_le_abs z)\n\n";
    oss << "private lemma weierstrassFactor1_ne_zero {z : ℂ} (hz : z ≠ 1) :\n";
    oss << "    weierstrassFactor1 z ≠ 0 := by\n";
    oss << "  intro h0; dsimp [weierstrassFactor1] at h0\n";
    oss << "  rcases mul_eq_zero.mp h0 with h1z | hexp\n";
    oss << "  · exact hz (eq_comm.mp (sub_eq_zero.mp h1z))\n";
    oss << "  · exact Complex.exp_ne_zero z hexp\n\n";
    oss << "private lemma weierstrass_factor_abs_ge_dist (z : ℂ) :\n";
    oss << "    Real.exp (-‖z‖) * Complex.abs (1 - z) ≤ Complex.abs (weierstrassFactor1 z) := by\n";
    oss << "  have hexp : Real.exp (-‖z‖) ≤ Complex.abs (Complex.exp z) := by\n";
    oss << "    rw [Complex.abs_exp]\n";
    oss << "    have hre : -‖z‖ ≤ z.re := by\n";
    oss << "      have h := Complex.abs_re_le_abs z; rw [← Complex.norm_eq_abs] at h; linarith\n";
    oss << "    exact Real.exp_le_exp_of_le hre\n";
    oss << "  dsimp [weierstrassFactor1]\n";
    oss << "  calc Real.exp (-‖z‖) * Complex.abs (1 - z) ≤ Complex.abs (Complex.exp z) * Complex.abs (1 - z) := by gcongr\n";
    oss << "    _ = Complex.abs ((1 - z) * Complex.exp z) := by rw [← Complex.abs.map_mul, mul_comm]\n";
    oss << "    _ = Complex.abs (weierstrassFactor1 z) := rfl\n\n";
    oss << "lemma weierstrass_log_norm_le_head_envelope_small {z : ℂ} (hz1 : z ≠ 1) {R : ℝ} (hR : 1 ≤ R)\n";
    oss << "    (hz : ‖z‖ ≤ R) (hhalf : ‖z‖ ≤ (1 / 2 : ℝ)) :\n";
    oss << "    ‖Complex.log (weierstrassFactor1 z)‖ ≤\n";
    oss << "      Real.log (1 + R) + R + 2 * Real.pi + 2 * R := by\n";
    oss << "  have hfac_ub' : Complex.abs (weierstrassFactor1 z) ≤ (1 + R) * Real.exp R := by\n";
    oss << "    have hub : (1 + ‖z‖) * Real.exp ‖z‖ ≤ (1 + R) * Real.exp R := by\n";
    oss << "      gcongr <;> linarith [norm_nonneg z, hz, hR]\n";
    oss << "    exact le_trans (by simpa [Complex.norm_eq_abs] using weierstrass_factor_norm_le z) hub\n";
    oss << "  rw [Complex.norm_eq_abs]\n";
    oss << "  refine le_trans (complex_log_norm_le_log_abs_add_pi _) ?_\n";
    oss << "  have hmono :=\n";
    oss << "    Real.log_le_log (Complex.abs.pos (weierstrassFactor1_ne_zero hz1)) hfac_ub'\n";
    oss << "  have hub_log : Real.log ((1 + R) * Real.exp R) = Real.log (1 + R) + R := by\n";
    oss << "    rw [Real.log_mul (by positivity) (Real.exp_ne_zero _)]; simp [Real.log_exp]\n";
    oss << "  nlinarith [hmono, le_of_eq hub_log, Real.pi_nonneg, hR, Real.two_pi_pos, Real.pi_le_four]\n\n";
    oss << "private lemma weierstrass_factor_abs_le (z : ℂ) :\n";
    oss << "    Complex.abs (weierstrassFactor1 z) ≤ (1 + ‖z‖) * Real.exp ‖z‖ := by\n";
    oss << "  simpa [Complex.norm_eq_abs] using weierstrass_factor_norm_le z\n\n";
    oss << "private lemma norm_sub_one_le_abs_one_sub (z : ℂ) :\n";
    oss << "    (‖z‖ - 1) ≤ Complex.abs (1 - z) := by\n";
    oss << "  have h' : ‖z‖ ≤ Complex.abs (1 - z) + 1 := by\n";
    oss << "    have h := norm_add_le (z - 1) (1 : ℂ)\n";
    oss << "    rw [sub_add_cancel, norm_one, norm_sub_rev] at h\n";
    oss << "    simpa [Complex.norm_eq_abs] using h\n";
    oss << "  linarith\n\n";
    oss << "private lemma norm_sub_log_sub_one_le_at_R {t R : ℝ} (ht : (2 : ℝ) ≤ t) (htR : t ≤ R)\n";
    oss << "    (hR : (2 : ℝ) ≤ R) :\n";
    oss << "    t - Real.log (t - 1) ≤ R - Real.log (R - 1) := by\n";
    oss << "  suffices h : t - R ≤ Real.log (t - 1) - Real.log (R - 1) by linarith\n";
    oss << "  have hdiv : (t - 1) / (R - 1) ≤ 1 := by\n";
    oss << "    rw [div_le_one_iff]\n";
    oss << "    rcases le_or_lt (R - 1) 0 with hR1 | hR1\n";
    oss << "    · nlinarith [htR, ht, hR]\n";
    oss << "    · left; nlinarith [htR, ht, hR]\n";
    oss << "  have hlog : Real.log ((t - 1) / (R - 1)) ≤ 0 :=\n";
    oss << "    Real.log_nonpos (by nlinarith [ht]) hdiv\n";
    oss << "  simpa [Real.log_div (by nlinarith [ht]) (by nlinarith [htR, ht, hR])] using hlog\n\n";
    oss << "lemma weierstrass_log_rest_large_norm_le_head_envelope {z : ℂ} (hz1 : z ≠ 1) {R : ℝ}\n";
    oss << "    (hR : (6 : ℝ) ≤ R) (hz : ‖z‖ ≤ R) (hlarge : (2 : ℝ) ≤ ‖z‖)\n";
    oss << "    (hRcap : R ≤ pinnedGenusOneLogMaxBallRadius) :\n";
    oss << "    ‖Complex.log (weierstrassFactor1 z)‖ ≤\n";
    oss << "      Real.log (1 + R) + R + 2 * Real.pi + 2 * R := by\n";
    oss << "  have hfac_ub := weierstrass_factor_abs_le z\n";
    oss << "  have hub : (1 + ‖z‖) * Real.exp ‖z‖ ≤ (1 + R) * Real.exp R := by\n";
    oss << "    gcongr <;> linarith [norm_nonneg z, hz, hR]\n";
    oss << "  have hfac_ub' : Complex.abs (weierstrassFactor1 z) ≤ (1 + R) * Real.exp R := le_trans hfac_ub hub\n";
    oss << "  have h1zpos : 0 < Complex.abs (1 - z) := Complex.abs.pos (sub_ne_zero.mpr (Ne.symm hz1))\n";
    oss << "  have hden : Complex.abs (1 - z) ≤ Real.exp ‖z‖ := by\n";
    oss << "    have hdist : Complex.abs (1 - z) ≤ 1 + ‖z‖ := by simpa [Complex.norm_eq_abs] using norm_sub_le 1 z\n";
    oss << "    have hone : (1 : ℝ) ≤ Real.exp ‖z‖ := Real.add_one_le_exp ‖z‖\n";
    oss << "    linarith [hdist, hone, norm_nonneg z]\n";
    oss << "  have h1mz := norm_sub_one_le_abs_one_sub z\n";
    oss << "  have hub_ratio :\n";
    oss << "      Complex.abs (weierstrassFactor1 z) ≤\n";
    oss << "        (1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z) := by\n";
    oss << "    have hstep : Real.exp R * Complex.abs (1 - z) ≤ Real.exp (R + ‖z‖) := by\n";
    oss << "      rw [Real.exp_add]\n";
    oss << "      exact mul_le_mul_of_nonneg_left hden (Real.exp_pos R).le\n";
    oss << "    have hmul : (1 + R) * Real.exp R * Complex.abs (1 - z) ≤ (1 + R) * Real.exp (R + ‖z‖) := by\n";
    oss << "      simpa [mul_assoc] using mul_le_mul_of_nonneg_left hstep (by linarith [hR])\n";
    oss << "    exact le_trans hfac_ub' ((le_div_iff₀ h1zpos).mpr hmul)\n";
    oss << "  have hlogabs :\n";
    oss << "      |Real.log (Complex.abs (weierstrassFactor1 z))| ≤\n";
    oss << "        Real.log ((1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z)) := by\n";
    oss << "    have hmono :=\n";
    oss << "      Real.log_le_log (Complex.abs.pos (weierstrassFactor1_ne_zero hz1)) hub_ratio\n";
    oss << "    rcases le_total 0 (Real.log (Complex.abs (weierstrassFactor1 z))) with ht | ht\n";
    oss << "    · rw [_root_.abs_of_nonneg ht]; exact hmono\n";
    oss << "    · rw [abs_of_nonpos ht]\n";
    oss << "      have hfac_lo := weierstrass_factor_abs_ge_dist z\n";
    oss << "      have hlo_log := Real.log_le_log (mul_pos (Real.exp_pos _) h1zpos) hfac_lo\n";
    oss << "      rw [Real.log_mul (Real.exp_ne_zero (-‖z‖)) h1zpos.ne', Real.log_exp] at hlo_log\n";
    oss << "      have hcap : -Real.log (Complex.abs (weierstrassFactor1 z)) ≤\n";
    oss << "          -Real.log (Complex.abs (1 - z)) + ‖z‖ := by linarith [hlo_log]\n";
    oss << "      have hle : -Real.log (Complex.abs (1 - z)) + ‖z‖ ≤\n";
    oss << "          Real.log ((1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z)) := by\n";
    oss << "        have hpos : 0 < (1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z) := by positivity\n";
    oss << "        have hexp : Real.exp (-Real.log (Complex.abs (1 - z)) + ‖z‖) ≤\n";
    oss << "            (1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z) := by\n";
    oss << "          rw [Real.exp_add, Real.exp_neg, Real.exp_log h1zpos, div_eq_mul_inv, mul_assoc]\n";
    oss << "          suffices h : Real.exp ‖z‖ ≤ (1 + R) * Real.exp (R + ‖z‖) by\n";
    oss << "            field_simp [h1zpos.ne']; gcongr; exact h\n";
    oss << "          have hone : (1 : ℝ) ≤ (1 + R) * Real.exp R := by nlinarith [hR, Real.add_one_le_exp R]\n";
    oss << "          calc Real.exp ‖z‖ = 1 * Real.exp ‖z‖ := by ring\n";
    oss << "            _ ≤ (1 + R) * Real.exp R * Real.exp ‖z‖ := by nlinarith [hone, Real.exp_pos ‖z‖]\n";
    oss << "            _ = (1 + R) * Real.exp (R + ‖z‖) := by rw [Real.exp_add, mul_assoc]\n";
    oss << "        exact (Real.le_log_iff_exp_le hpos).mpr hexp\n";
    oss << "      linarith [hcap, hle]\n";
    oss << "  rw [Complex.norm_eq_abs]\n";
    oss << "  refine le_trans (complex_log_norm_le_log_abs_add_pi _) ?_\n";
    oss << "  have hfinal :\n";
    oss << "      Real.log ((1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z)) ≤\n";
    oss << "        Real.log (1 + R) + R + 2 * R + Real.pi := by\n";
    oss << "    have hsplit :\n";
    oss << "        Real.log ((1 + R) * Real.exp (R + ‖z‖) / Complex.abs (1 - z)) =\n";
    oss << "          Real.log (1 + R) + R + ‖z‖ - Real.log (Complex.abs (1 - z)) := by\n";
    oss << "      rw [Real.log_div (by positivity) h1zpos.ne', Real.log_mul (by linarith [hR]) (Real.exp_ne_zero _)]\n";
    oss << "      simp only [Real.log_exp, add_sub_assoc, sub_eq_add_neg]; abel\n";
    oss << "    have hlogdist : Real.log (‖z‖ - 1) ≤ Real.log (Complex.abs (1 - z)) :=\n";
    oss << "      Real.log_le_log (by nlinarith [hlarge] : 0 < ‖z‖ - 1) h1mz\n";
    oss << "    have hupper : ‖z‖ - Real.log (Complex.abs (1 - z)) ≤ ‖z‖ - Real.log (‖z‖ - 1) := by\n";
    oss << "      linarith [hlogdist]\n";
    oss << "    have hcore : ‖z‖ - Real.log (‖z‖ - 1) ≤ 2 * R + Real.pi := by\n";
    oss << "      have hAtR := norm_sub_log_sub_one_le_at_R (t := ‖z‖) hlarge hz (by linarith [hR])\n";
    oss << "      have hRbound : R - Real.log (R - 1) ≤ 2 * R + Real.pi := by\n";
    oss << "        have hlognonneg : 0 ≤ Real.log (R - 1) := Real.log_nonneg (by linarith [hR])\n";
    oss << "        nlinarith [hR, Real.pi_pos, hlognonneg]\n";
    oss << "      linarith [hAtR, hRbound]\n";
    oss << "    rw [hsplit]\n";
    oss << "    have hL :\n";
    oss << "        Real.log (1 + R) + R + ‖z‖ - Real.log (Complex.abs (1 - z)) ≤\n";
    oss << "          Real.log (1 + R) + R + (‖z‖ - Real.log (‖z‖ - 1)) := by linarith [hupper]\n";
    oss << "    linarith [hL, add_le_add_right hcore (Real.log (1 + R) + R)]\n";
    oss << "  linarith [hlogabs, hfinal, Real.pi_nonneg]\n\n";
    oss << "lemma weierstrass_log_norm_le_head_envelope_ratio {z : ℂ} (hz1 : z ≠ 1) {R ρ γ : ℝ}\n";
    oss << "    (hR : (4 : ℝ) ≤ R) (hγ : (1 : ℝ) ≤ γ) (hρpos : 0 < ρ) (hρR : ρ ≤ R) (hργ : ρ * γ ≤ R)\n";
    oss << "    (hz : ‖z‖ ≤ ρ) (hRcap : R ≤ pinnedGenusOneLogMaxBallRadius) :\n";
    oss << "    ‖Complex.log (weierstrassFactor1 z)‖ ≤\n";
    oss << "      Real.log (1 + R) + R + 2 * Real.pi + 2 * R := by\n";
    oss << "  rcases le_or_gt ‖z‖ (1 / 2 : ℝ) with hhalf | hhalf\n";
    oss << "  · have hR1 : (1 : ℝ) ≤ R := le_trans (by norm_num) hR\n";
    oss << "    exact weierstrass_log_norm_le_head_envelope_small hz1 hR1 (le_trans hz hρR) hhalf\n";
    oss << "  · have hR6 : (6 : ℝ) ≤ R := by nlinarith [hhalf, hz, hρpos, hργ, hγ, hρR]\n";
    oss << "    by_cases hz2 : (2 : ℝ) ≤ ‖z‖\n";
    oss << "    · exact weierstrass_log_rest_large_norm_le_head_envelope hz1 hR6 (le_trans hz hρR) hz2 hRcap\n";
    oss << "    · have hfac_ub' : Complex.abs (weierstrassFactor1 z) ≤ (1 + R) * Real.exp R := by\n";
    oss << "        have hub : (1 + ‖z‖) * Real.exp ‖z‖ ≤ (1 + R) * Real.exp R := by\n";
    oss << "          gcongr <;> linarith [norm_nonneg z, hz, hρR, hR]\n";
    oss << "        exact le_trans (weierstrass_factor_abs_le z) hub\n";
    oss << "      rw [Complex.norm_eq_abs]\n";
    oss << "      refine le_trans (complex_log_norm_le_log_abs_add_pi _) ?_\n";
    oss << "      have hmono :=\n";
    oss << "        Real.log_le_log (Complex.abs.pos (weierstrassFactor1_ne_zero hz1)) hfac_ub'\n";
    oss << "      have hub_log : Real.log ((1 + R) * Real.exp R) = Real.log (1 + R) + R := by\n";
    oss << "        rw [Real.log_mul (by positivity) (Real.exp_ne_zero _)]; simp [Real.log_exp]\n";
    oss << "      nlinarith [hmono, le_of_eq hub_log, Real.pi_nonneg, hR, hR6, hRcap, Real.two_pi_pos,\n";
    oss << "        Real.pi_le_four, hz, hhalf, hz2, hργ, hγ, hρpos, hρR]\n\n";
    oss << "lemma weierstrass_log_norm_le_head_envelope {z : ℂ} (hz1 : z ≠ 1) {R : ℝ} (hR : (4 : ℝ) ≤ R)\n";
    oss << "    (hz : ‖z‖ ≤ R) (hRcap : R ≤ pinnedGenusOneLogMaxBallRadius) :\n";
    oss << "    ‖Complex.log (weierstrassFactor1 z)‖ ≤\n";
    oss << "      Real.log (1 + R) + R + 2 * Real.pi + 2 * R :=\n";
    oss << "  weierstrass_log_norm_le_head_envelope_ratio hz1 hR (by norm_num) (by nlinarith [hz, hR]) (le_rfl)\n";
    oss << "    (by nlinarith [hz, hR]) hz hRcap\n\n";
    oss << "end HPAnalysis\n";
    return oss.str();
}

std::string emit_marshal_genus_one_log_bounds_lean(const Heat::XiHadamardReport& r) {
    std::ostringstream oss;
    oss << "import Analysis.MarshalXiHadamardAnaVmCert\n";
    oss << "import Analysis.MarshalGenusOneLogAnalyticBridge\n";
    oss << "import Analysis.GenusOneLogBoundsTail\n";
    oss << "import Analysis.MarshalLogSummability\n\n";
    emit_header(oss, r, "AnaVM genus-1 log bounds — MRS/C++ cert pins (head majorant).");
    oss << "namespace HPAnalysis\n\n";
    oss << "open Complex Real Set Metric\n\n";
    oss << "noncomputable def marshalLogHeadMajorant (_s : ℂ) (_r : ℝ) : ℝ :=\n";
    oss << "  pinnedAnaVmGenusOneLogHeadMajorant\n\n";
    oss << "theorem marshalLogHeadMajorant_pos (_s : ℂ) (_r : ℝ) :\n";
    oss << "    0 < marshalLogHeadMajorant _s _r := by\n";
    oss << "  dsimp [marshalLogHeadMajorant, pinnedAnaVmGenusOneLogHeadMajorant]\n";
    oss << "  exact pinnedAnaVmGenusOneLogHeadMajorant_pos\n\n";
    oss << "lemma marshal_log_factor_norm_le_coarse_on_closedBall (s : ℂ) {r : ℝ} (hr : 0 < r) {w : ℂ}\n";
    oss << "    (hw : w ∈ closedBall s r) (n : ℕ) :\n";
    oss << "    ‖Complex.log (spectralDetFactor marshalDiscreteSpectrum w n)‖ ≤\n";
    oss << "      marshalLogHeadMajorant s r := by\n";
    oss << "  set z := w / criticalLineParam (marshalRiemannZeroHeight n)\n";
    oss << "  set Rmarshal := ‖s‖ + (r + 1)\n";
    oss << "  set ρ := Rmarshal / marshalRiemannZeroHeight n\n";
    oss << "  have hfac :\n";
    oss << "      spectralDetFactor marshalDiscreteSpectrum w n = weierstrassFactor1 z := by\n";
    oss << "    dsimp [spectralDetFactor, spectralXiFactor, z]; rfl\n";
    oss << "  rw [hfac]\n";
    oss << "  by_cases hz1 : z = 1\n";
    oss << "  · rw [hz1, weierstrassFactor1]; simp [Complex.log_zero]\n";
    oss << "    exact le_trans (by positivity) (marshalLogHeadMajorant_pos s r).le\n";
    oss << "  · have hratio := marshal_ratio_norm_le_on_closedBall s hr hw n\n";
    oss << "    have hγ1 := marshalRiemannZeroHeight_ge_one n\n";
    oss << "    have hρpos : 0 < ρ := by dsimp [ρ, Rmarshal]; positivity\n";
    oss << "    have hρR : ρ ≤ Rmarshal := by\n";
    oss << "      dsimp [ρ, Rmarshal]; exact div_le_self (by nlinarith [hr, norm_nonneg s]) hγ1\n";
    oss << "    have hz : ‖z‖ ≤ ρ := by dsimp [ρ, Rmarshal]; exact hratio\n";
    oss << "    have hR4 : (4 : ℝ) ≤ Rmarshal := by dsimp [Rmarshal]; nlinarith [hr, norm_nonneg s]\n";
    oss << "    have henvelope :=\n";
    oss << "      weierstrass_log_norm_le_head_envelope_ratio hz1 hR4 hγ1 hρpos hρR (by\n";
    oss << "        dsimp [ρ, Rmarshal]; nlinarith [hratio, hγ1]) hz (by\n";
    oss << "        dsimp [Rmarshal]\n";
    oss << "        nlinarith [hr, norm_nonneg s, hγ1, pinnedAnaVmGenusOneLogMaxBallRadius])\n";
    oss << "    have hpin := pinnedAnaVmGenusOneLogHeadMajorant_ge_ratio_envelope Rmarshal (by linarith [hR4])\n";
    oss << "      (by dsimp [Rmarshal]; nlinarith [hr, norm_nonneg s, hγ1, pinnedAnaVmGenusOneLogMaxBallRadius])\n";
    oss << "    dsimp [marshalLogHeadMajorant, pinnedAnaVmGenusOneLogHeadMajorant]\n";
    oss << "    exact le_trans henvelope hpin\n\n";
    oss << "theorem marshal_genus_one_log_summability_closed : MarshalGenusOneLogSummability :=\n";
    oss << "  marshal_genus_one_log_summability_proved\n\n";
    oss << "end HPAnalysis\n";
    return oss.str();
}

std::string sibling_lean_path(const std::string& cert_path, const char* filename) {
    const auto pos = cert_path.find_last_of("/\\");
    if (pos == std::string::npos) return filename;
    return cert_path.substr(0, pos + 1) + filename;
}

}  // namespace

XiHadamardLeanEmitRefusal xi_hadamard_lean_emit_refusal(const Heat::XiHadamardReport& report) {
    if (!report.proof_chain_closed) return XiHadamardLeanEmitRefusal::ProofChainOpen;
    if (!report.non_circular_architecture_ok || report.proof_graph.circular_logic_detected)
        return XiHadamardLeanEmitRefusal::CircularGraph;
    if (!xi_hadamard_report_bounds_ok(report)) return XiHadamardLeanEmitRefusal::BoundsExceedTolerance;
    return XiHadamardLeanEmitRefusal::None;
}

bool emit_xi_hadamard_lean_artifacts(const std::string& cert_lean_path,
                                     const std::string& canonical_lean_path,
                                     const std::string& rh_closure_lean_path,
                                     const Heat::XiHadamardReport& report,
                                     XiHadamardLeanEmitOptions opts) {
    const auto refusal = xi_hadamard_lean_emit_refusal(report);
    if (refusal != XiHadamardLeanEmitRefusal::None) {
        if (!opts.quiet_refusal) {
            switch (refusal) {
                case XiHadamardLeanEmitRefusal::ProofChainOpen:
                    std::cerr << "AnaLeanEmitter: proof_chain_closed=false; refusing Lean emission\n";
                    break;
                case XiHadamardLeanEmitRefusal::CircularGraph:
                    std::cerr << "AnaLeanEmitter: circular proof graph; refusing Lean emission\n";
                    break;
                case XiHadamardLeanEmitRefusal::BoundsExceedTolerance:
                    std::cerr << "AnaLeanEmitter: audit bounds exceed MRS tolerance; refusing Lean emission\n";
                    break;
                default:
                    break;
            }
        }
        return false;
    }
    const std::string cert_body = emit_cert_lean(report);
    const std::string canonical_body = emit_canonical_product_lean(report);
    const std::string rh_body = emit_rh_closure_lean(report);
    const std::string bridge_path = sibling_lean_path(cert_lean_path, "MarshalGenusOneLogAnalyticBridge.lean");
    const std::string bounds_path = sibling_lean_path(cert_lean_path, "MarshalAnaVmGenusOneLogBounds.lean");
    const std::string bridge_body = emit_genus_one_log_analytic_bridge_lean(report);
    const std::string bounds_body = emit_marshal_genus_one_log_bounds_lean(report);
    if (!write_file(cert_lean_path, cert_body)) {
        std::cerr << "AnaLeanEmitter: failed to write " << cert_lean_path << "\n";
        return false;
    }
    if (!write_file(canonical_lean_path, canonical_body)) {
        std::cerr << "AnaLeanEmitter: failed to write " << canonical_lean_path << "\n";
        return false;
    }
    if (!rh_closure_lean_path.empty() && !write_file(rh_closure_lean_path, rh_body)) {
        std::cerr << "AnaLeanEmitter: failed to write " << rh_closure_lean_path << "\n";
        return false;
    }
    if (!write_file(bridge_path, bridge_body)) {
        std::cerr << "AnaLeanEmitter: failed to write " << bridge_path << "\n";
        return false;
    }
    if (!write_file(bounds_path, bounds_body)) {
        std::cerr << "AnaLeanEmitter: failed to write " << bounds_path << "\n";
        return false;
    }
    const auto validation = validate_xi_hadamard_lean_bundle(
        cert_body, canonical_body, rh_body, bridge_body, bounds_body, report);
    if (!validation.ok) {
        for (const auto& issue : validation.issues)
            std::cerr << "AnaLeanEmitter: codegen validation [" << issue.role << "]: "
                      << issue.message << "\n";
        return false;
    }
    std::cout << "AnaVM Lean cert: " << cert_lean_path << "\n";
    std::cout << "AnaVM Lean bridge: " << canonical_lean_path << "\n";
    std::cout << "AnaVM Lean genus-1 analytic bridge: " << bridge_path << "\n";
    std::cout << "AnaVM Lean genus-1 bounds: " << bounds_path << "\n";
    if (!rh_closure_lean_path.empty())
        std::cout << "AnaVM Lean RH closure: " << rh_closure_lean_path << "\n";
    return true;
}

}  // namespace Marshal::AnaVM
