import Analysis.CertifiedBounds
import Mathlib.Tactic

/-!
  AUTO-GENERATED by EmitMarshalLadderCert.py — do not edit by hand.
  Sources: anavm_bsd_proof.json, anavm_hodge_proof.json, anavm_goldbach_proof.json
-/

namespace HPAnalysis.Ladder

open Real

/-! ## BSD (curve 37a, GL(2)) -/

noncomputable def pinnedBSDAlgebraicRank : ℕ := 1

noncomputable def pinnedBSDKernelMultiplicity : ℕ := 1

noncomputable def pinnedBSDLGridRelGapUb : ℝ := (3 : ℝ) / 100

noncomputable def pinnedBSDShaResolventGapUb : ℝ := (2 : ℝ) / 1

noncomputable def pinnedBSDLGridRelGapMeasured : ℝ := (0 : ℝ) / 1000000000

noncomputable def pinnedBSDShaResolventGapMeasured : ℝ := (739946 : ℝ) / 1000000

theorem pinned_bsd_rank_match :
    pinnedBSDKernelMultiplicity = pinnedBSDAlgebraicRank := by
  norm_num [pinnedBSDKernelMultiplicity, pinnedBSDAlgebraicRank]

theorem pinned_bsd_l_grid_gap_bounded :
    pinnedBSDLGridRelGapMeasured < pinnedBSDLGridRelGapUb := by
  norm_num [pinnedBSDLGridRelGapMeasured, pinnedBSDLGridRelGapUb]

theorem pinned_bsd_sha_gap_bounded :
    pinnedBSDShaResolventGapMeasured < pinnedBSDShaResolventGapUb := by
  norm_num [pinnedBSDShaResolventGapMeasured, pinnedBSDShaResolventGapUb]

/-! ## Hodge (K3 stub, GL(3)) -/

noncomputable def pinnedHodgePredictedMultiplicity : ℕ := 20

noncomputable def pinnedHodgeKernelMultiplicity : ℕ := 20

theorem pinned_hodge_h11_match :
    pinnedHodgeKernelMultiplicity = pinnedHodgePredictedMultiplicity := by
  norm_num [pinnedHodgeKernelMultiplicity, pinnedHodgePredictedMultiplicity]

/-! ## Goldbach (GL(2) ellipse/Heegner) -/

noncomputable def pinnedGoldbachMajorArcThreshold : ℝ := (45 : ℝ) / 100

noncomputable def pinnedGoldbachMinorArcUb : ℝ := (1 : ℝ) / 100

noncomputable def pinnedGoldbachMajorArcMass : ℝ := (492318 : ℝ) / 1000000

noncomputable def pinnedGoldbachMinorArcBound : ℝ := (1436631 : ℝ) / 1000000000

noncomputable def pinnedGoldbachN0 : ℕ := 4

theorem pinned_goldbach_major_arc_ok :
    pinnedGoldbachMajorArcThreshold ≤ pinnedGoldbachMajorArcMass := by
  norm_num [pinnedGoldbachMajorArcThreshold, pinnedGoldbachMajorArcMass]

theorem pinned_goldbach_minor_arc_ok :
    pinnedGoldbachMinorArcBound < pinnedGoldbachMinorArcUb := by
  norm_num [pinnedGoldbachMinorArcBound, pinnedGoldbachMinorArcUb]

end HPAnalysis.Ladder
