import Analysis.CertifiedBounds
import Mathlib.Tactic

/-!
  AUTO-GENERATED by AnaVM AnaLeanEmitter — do not edit by hand.
  Pinned XiHadamard audit numerics (norm_num only).
  program=marshal_hadamard_identification proof_chain_closed=true acyclic=true
-/

namespace HPAnalysis

noncomputable def pinnedAnaVmXiHadamardGridCount : ℕ := 1000

noncomputable def pinnedAnaVmXiHadamardIdentTruncationN : ℕ := 50000

noncomputable def pinnedAnaVmXiHadamardZeroTruncation : ℕ := 50000

noncomputable def pinnedAnaVmXiHadamardMaxGridRelGap : ℝ := 0.02582491748783293

noncomputable def pinnedAnaVmXiHadamardGridRelGapUb : ℝ := 0.029999999999999999

noncomputable def pinnedAnaVmXiHadamardMaxGridMultDev : ℝ := 0.025824917487833023

noncomputable def pinnedAnaVmXiHadamardGridMultDevUb : ℝ := 0.029999999999999999

noncomputable def pinnedAnaVmXiHadamardMaxTailBoundDecades : ℝ := 0.052592769596093339

noncomputable def pinnedAnaVmXiHadamardTailBoundDecadesUb : ℝ := 0.14999999999999999

noncomputable def pinnedAnaVmXiHadamardMaxLogTimesGamma2 : ℝ := 12.500000390596716

noncomputable def pinnedAnaVmXiHadamardMaxPartialLogAbsSum : ℝ := 0.28468493459764083

noncomputable def pinnedAnaVmXiHadamardLogPartialSumUb : ℝ := 8

noncomputable def pinnedAnaVmGenusOneLogMaxBallRadius : ℝ := 31.006249023742555

noncomputable def pinnedAnaVmGenusOneLogHeadMajorant : ℝ := 105.52929894593478

noncomputable def pinnedAnaVmGenusOneLogMaxHeadEnvelope : ℝ := 102.76786354413389

noncomputable def pinnedAnaVmGenusOneLogCapDominantLogUb : ℝ :=
  Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + (1 / 2 : ℝ)

noncomputable def pinnedAnaVmGenusOneLogCapDominantExpUb : ℝ :=
  Real.exp pinnedAnaVmGenusOneLogCapDominantLogUb

noncomputable def pinnedAnaVmGenusOneLogCapExpUb : ℝ :=
  (1 + pinnedAnaVmGenusOneLogMaxBallRadius) * Real.exp 1

noncomputable def pinnedAnaVmGenusOneLogCapLogUb : ℝ :=
  Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + 1

noncomputable def pinnedAnaVmGenusOneLogCapLinear : ℝ := 93.018747071227665

noncomputable def pinnedAnaVmGenusOneLogCapTwoPiUb : ℝ := 8

noncomputable def pinnedAnaVmGenusOneLogCapSumUb : ℝ :=
  pinnedAnaVmGenusOneLogCapDominantLogUb + pinnedAnaVmGenusOneLogCapLinear +
    pinnedAnaVmGenusOneLogCapTwoPiUb

noncomputable def pinnedAnaVmGenusOneLogMajorantC : ℝ := 1.05

noncomputable def pinnedAnaVmXiHadamardMaxIdentGapDecades : ℝ := 0.073991550313265847

noncomputable def pinnedAnaVmXiHadamardIdentGapDecadesUb : ℝ := 0.14999999999999999

noncomputable def pinnedAnaVmHolomorphyMaxUniformGap : ℝ := 0.0040340576084326729

noncomputable def pinnedAnaVmHolomorphyUniformGapUb : ℝ := 0.01

def pinnedAnaVmXiHadamardGenusOneLogSummabilityOk : Bool := true

def pinnedAnaVmXiHadamardGridIdentificationOk : Bool := true

def pinnedAnaVmHolomorphyOk : Bool := true

def pinnedAnaVmXiHadamardProofChainClosed : Bool := true

theorem pinnedAnaVmXiHadamardMaxGridRelGap_bounded :
    pinnedAnaVmXiHadamardMaxGridRelGap < pinnedAnaVmXiHadamardGridRelGapUb := by
  unfold pinnedAnaVmXiHadamardMaxGridRelGap pinnedAnaVmXiHadamardGridRelGapUb
  norm_num

theorem pinnedAnaVmXiHadamardMaxGridMultDev_bounded :
    pinnedAnaVmXiHadamardMaxGridMultDev < pinnedAnaVmXiHadamardGridMultDevUb := by
  unfold pinnedAnaVmXiHadamardMaxGridMultDev pinnedAnaVmXiHadamardGridMultDevUb
  norm_num

theorem pinnedAnaVmXiHadamardMaxTailBoundDecades_bounded :
    pinnedAnaVmXiHadamardMaxTailBoundDecades < pinnedAnaVmXiHadamardTailBoundDecadesUb := by
  unfold pinnedAnaVmXiHadamardMaxTailBoundDecades pinnedAnaVmXiHadamardTailBoundDecadesUb
  norm_num

theorem pinnedAnaVmXiHadamardMaxIdentGapDecades_bounded :
    pinnedAnaVmXiHadamardMaxIdentGapDecades < pinnedAnaVmXiHadamardIdentGapDecadesUb := by
  unfold pinnedAnaVmXiHadamardMaxIdentGapDecades pinnedAnaVmXiHadamardIdentGapDecadesUb
  norm_num

theorem pinnedAnaVmHolomorphyMaxUniformGap_bounded :
    pinnedAnaVmHolomorphyMaxUniformGap < pinnedAnaVmHolomorphyUniformGapUb := by
  unfold pinnedAnaVmHolomorphyMaxUniformGap pinnedAnaVmHolomorphyUniformGapUb
  norm_num

theorem pinnedAnaVmXiHadamardMaxPartialLogAbsSum_bounded :
    pinnedAnaVmXiHadamardMaxPartialLogAbsSum < pinnedAnaVmXiHadamardLogPartialSumUb := by
  unfold pinnedAnaVmXiHadamardMaxPartialLogAbsSum pinnedAnaVmXiHadamardLogPartialSumUb
  norm_num

theorem pinnedAnaVmGenusOneLogHeadMajorant_pos :
    0 < pinnedAnaVmGenusOneLogHeadMajorant := by
  unfold pinnedAnaVmGenusOneLogHeadMajorant
  norm_num

private lemma pinnedAnaVmGenusOneLogCapExpUb_log_eq :
    Real.log pinnedAnaVmGenusOneLogCapExpUb =
      Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + 1 := by
  dsimp [pinnedAnaVmGenusOneLogCapExpUb]
  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by
    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num
  rw [Real.log_mul (ne_of_gt hpos) (ne_of_gt (Real.exp_pos 1))]
  rw [Real.log_exp]

theorem pinnedAnaVmGenusOneLogCapOnePlusR_le_exp_capLogUb :
    (1 + pinnedAnaVmGenusOneLogMaxBallRadius) ≤
      Real.exp (pinnedAnaVmGenusOneLogCapLogUb - 1) := by
  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by
    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num
  have heq : Real.exp (pinnedAnaVmGenusOneLogCapLogUb - 1) = 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by
    dsimp [pinnedAnaVmGenusOneLogCapLogUb]
    calc Real.exp (Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) + 1 - 1)
        = Real.exp (Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius)) := by ring_nf
      _ = 1 + pinnedAnaVmGenusOneLogMaxBallRadius := Real.exp_log hpos
  exact le_of_eq heq.symm

private theorem pinnedAnaVmGenusOneLogCapLog_lt_four :
    Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) < (4 : ℝ) := by
  have hpos : 0 < 1 + pinnedAnaVmGenusOneLogMaxBallRadius := by
    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num
  rw [Real.log_lt_iff_lt_exp hpos]
  have h1 := Real.exp_one_gt_d9
  have h2 : (7 : ℝ) < Real.exp 2 := by
    have hpow : (2.7182818283 : ℝ) * 2.7182818283 < Real.exp 1 * Real.exp 1 := by
      nlinarith [h1, Real.exp_pos 1]
    rw [← Real.exp_add, show (1 + 1 : ℝ) = 2 from by norm_num] at hpow
    nlinarith [hpow, Real.exp_pos 1, Real.exp_pos 2]
  have h3 : (10 : ℝ) < Real.exp 3 := by
    have hpow : (10 : ℝ) < Real.exp 1 * Real.exp 2 := by nlinarith [h1, h2, Real.exp_pos 1, Real.exp_pos 2]
    calc (10 : ℝ) < Real.exp 1 * Real.exp 2 := hpow
      _ = Real.exp 3 := by rw [← Real.exp_add, show (1 + 2 : ℝ) = 3 from by norm_num]
  have h4 : (33 : ℝ) < Real.exp 4 := by
    have h22 : (49 : ℝ) < Real.exp 2 * Real.exp 2 := by nlinarith [h2, Real.exp_pos 2]
    have h44 : Real.exp 4 = Real.exp 2 * Real.exp 2 := by
      rw [← Real.exp_add, show (2 + 2 : ℝ) = 4 from by norm_num]
    nlinarith [h22, h44]
  have hr : (1 + pinnedAnaVmGenusOneLogMaxBallRadius) < (33 : ℝ) := by
    unfold pinnedAnaVmGenusOneLogMaxBallRadius; norm_num
  exact lt_trans hr h4

theorem pinnedAnaVmGenusOneLogCapSumUb_le_majorant :
    pinnedAnaVmGenusOneLogCapSumUb ≤ pinnedAnaVmGenusOneLogHeadMajorant := by
  have hlog := le_of_lt pinnedAnaVmGenusOneLogCapLog_lt_four
  unfold pinnedAnaVmGenusOneLogCapSumUb pinnedAnaVmGenusOneLogCapDominantLogUb
    pinnedAnaVmGenusOneLogCapLinear pinnedAnaVmGenusOneLogCapTwoPiUb
    pinnedAnaVmGenusOneLogHeadMajorant
  nlinarith [hlog, Real.pi_lt_four]

theorem pinnedAnaVmGenusOneLogCapRatio_le_majorant :
    Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) +
        pinnedAnaVmGenusOneLogMaxBallRadius + 2 * Real.pi +
        2 * pinnedAnaVmGenusOneLogMaxBallRadius ≤ pinnedAnaVmGenusOneLogHeadMajorant := by
  have hpi : 2 * Real.pi ≤ pinnedAnaVmGenusOneLogCapTwoPiUb := by
    unfold pinnedAnaVmGenusOneLogCapTwoPiUb
    have hπhi : Real.pi < (4 : ℝ) := Real.pi_lt_four
    nlinarith [hπhi]
  have hlin : pinnedAnaVmGenusOneLogMaxBallRadius + 2 * pinnedAnaVmGenusOneLogMaxBallRadius ≤
      pinnedAnaVmGenusOneLogCapLinear := by
    unfold pinnedAnaVmGenusOneLogCapLinear pinnedAnaVmGenusOneLogMaxBallRadius
    norm_num
  have hlog : Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) ≤
      pinnedAnaVmGenusOneLogCapDominantLogUb := by
    dsimp [pinnedAnaVmGenusOneLogCapDominantLogUb]
    linarith
  have hcap : pinnedAnaVmGenusOneLogCapDominantLogUb + pinnedAnaVmGenusOneLogCapLinear +
      pinnedAnaVmGenusOneLogCapTwoPiUb ≤ pinnedAnaVmGenusOneLogCapSumUb := by
    dsimp [pinnedAnaVmGenusOneLogCapSumUb]
    exact le_rfl
  linarith [hlog, hpi, hlin, hcap, pinnedAnaVmGenusOneLogCapSumUb_le_majorant]

theorem pinnedAnaVmGenusOneLogMaxHeadEnvelope_lt_majorant :
    pinnedAnaVmGenusOneLogMaxHeadEnvelope < pinnedAnaVmGenusOneLogHeadMajorant := by
  unfold pinnedAnaVmGenusOneLogMaxHeadEnvelope pinnedAnaVmGenusOneLogHeadMajorant
  norm_num

theorem pinnedAnaVmGenusOneLogHeadMajorant_ge_ratio_envelope {R : ℝ} (hR : 1 ≤ R)
    (hRcap : R ≤ pinnedAnaVmGenusOneLogMaxBallRadius) :
    Real.log (1 + R) + R + 2 * Real.pi + 2 * R ≤ pinnedAnaVmGenusOneLogHeadMajorant := by
  have hmono :
      Real.log (1 + R) + R + 2 * Real.pi + 2 * R ≤
        Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) +
          pinnedAnaVmGenusOneLogMaxBallRadius + 2 * Real.pi +
          2 * pinnedAnaVmGenusOneLogMaxBallRadius := by
    have hlog : Real.log (1 + R) ≤ Real.log (1 + pinnedAnaVmGenusOneLogMaxBallRadius) :=
      Real.log_le_log (by linarith [hR] : 0 < 1 + R)
        (by linarith [hRcap] : (1 + R : ℝ) ≤ 1 + pinnedAnaVmGenusOneLogMaxBallRadius)
    linarith [hlog, hRcap]
  exact le_trans hmono pinnedAnaVmGenusOneLogCapRatio_le_majorant

theorem pinnedAnaVm_xi_hadamard_audit_bounds_ok :
    pinnedAnaVmXiHadamardMaxGridRelGap < pinnedAnaVmXiHadamardGridRelGapUb ∧
      pinnedAnaVmXiHadamardMaxGridMultDev < pinnedAnaVmXiHadamardGridMultDevUb ∧
      pinnedAnaVmXiHadamardMaxTailBoundDecades < pinnedAnaVmXiHadamardTailBoundDecadesUb ∧
      pinnedAnaVmXiHadamardMaxIdentGapDecades < pinnedAnaVmXiHadamardIdentGapDecadesUb :=
  ⟨pinnedAnaVmXiHadamardMaxGridRelGap_bounded,
    pinnedAnaVmXiHadamardMaxGridMultDev_bounded,
    pinnedAnaVmXiHadamardMaxTailBoundDecades_bounded,
    pinnedAnaVmXiHadamardMaxIdentGapDecades_bounded⟩

theorem pinnedAnaVm_holomorphy_audit_bounds_ok :
    pinnedAnaVmHolomorphyMaxUniformGap < pinnedAnaVmHolomorphyUniformGapUb ∧
      pinnedAnaVmXiHadamardGenusOneLogSummabilityOk = true := by
  refine ⟨pinnedAnaVmHolomorphyMaxUniformGap_bounded, rfl⟩

end HPAnalysis
