import Analysis.MarshalXiHadamardAnaVmCert
import Analysis.MarshalWedgeCert
import Analysis.MarshalWedgeIdentityTheorem

/-!
  AUTO-GENERATED by AnaVM AnaLeanEmitter — do not edit by hand.
  AnaVM audit bridge — thin re-exports + norm_num pins.
  program=marshal_hadamard_identification proof_chain_closed=true acyclic=true
-/

namespace HPAnalysis

theorem marshalAnaVm_xi_hadamard_audit_ok :
    pinnedAnaVmXiHadamardMaxGridRelGap < pinnedAnaVmXiHadamardGridRelGapUb ∧
      pinnedAnaVmXiHadamardMaxGridMultDev < pinnedAnaVmXiHadamardGridMultDevUb ∧
      pinnedAnaVmXiHadamardMaxTailBoundDecades < pinnedAnaVmXiHadamardTailBoundDecadesUb ∧
      pinnedAnaVmXiHadamardMaxIdentGapDecades < pinnedAnaVmXiHadamardIdentGapDecadesUb :=
  pinnedAnaVm_xi_hadamard_audit_bounds_ok

theorem marshalAnaVm_genus_one_log_summability :
    MarshalGenusOneLogSummability :=
  marshal_genus_one_log_summability_closed

theorem marshalAnaVm_off_height_log_summability :
    MarshalOffHeightLogSummability :=
  marshal_off_height_log_summability_closed

end HPAnalysis
