import Analysis.MarshalXiHadamardAnaVmCert
import Analysis.MarshalAnaVmAnalyticClosure
import Analysis.MarshalHadamardWeierstrassClosure
import Analysis.MarshalInfiniteDetHolomorphy
import Analysis.MarshalWedgeCert
import Analysis.MarshalXiHadamardPublication

/-!
  AUTO-GENERATED by AnaVM AnaLeanEmitter — do not edit by hand.
  AnaVM RH spine — MRS v1 capstone wires MarshalAnaVmAnalyticClosure.
  program=marshal_hadamard_identification proof_chain_closed=true acyclic=true
-/

namespace HPAnalysis

theorem marshalAnaVm_holomorphy_proved : MarshalInfiniteDetHolomorphyOnWedge :=
  marshal_anavm_infinite_det_holomorphy_on_wedge_proved

theorem marshalAnaVm_wedge_grid_spectral_eq_riemannXi {n : ℕ} (hn : 1 ≤ n) :
    spectralDet marshalDiscreteSpectrum (marshalWedgeGridPt n) =
      riemannXi (marshalWedgeGridPt n) :=
  marshal_wedge_grid_spectral_eq_riemannXi hn

theorem marshalAnaVm_audit_ok :
    pinnedAnaVm_xi_hadamard_audit_bounds_ok ∧
      pinnedAnaVm_holomorphy_audit_bounds_ok :=
  ⟨pinnedAnaVm_xi_hadamard_audit_bounds_ok, pinnedAnaVm_holomorphy_audit_bounds_ok⟩

theorem marshal_mrs_weierstrass_identification : MarshalHadamardWeierstrassIdentification :=
  marshal_anavm_weierstrass_identification_proved

/-- **MRS v1 unconditional classical RH** (parameterless; no open analytic inputs). -/
theorem classical_rh_unconditional_mrs : ClassicalRiemannHypothesis :=
  classical_riemann_hypothesis_marshal_proved

/-- Publication alias aligned with C++ proof graph target name. -/
theorem classical_riemann_hypothesis_marshal_proved :
    ClassicalRiemannHypothesis :=
  classical_rh_unconditional_mrs

end HPAnalysis
