import Analysis.MarshalOdilyzkoZeroCert
import Mathlib.Tactic

/-!
  AUTO-GENERATED by tools/Analysis/MarshalOdilyzkoZeroCert.py — do not edit by hand.
  Pipeline: NtzGenerate(refine) → marshal-zero-verify → marshal_odilyzko_zero_cert.json
  Verified: 10000/10000
-/

namespace HPAnalysis

def pinnedOdilyzkoCertifiedCount : ℕ := 10000

def pinnedOdilyzkoVerifiedCount : ℕ := 10000

noncomputable def pinnedOdilyzkoZAbsTolerance : ℝ := 1e-10

theorem pinnedOdilyzko_cert_count_eq : pinnedOdilyzkoCertifiedCount = 10000 := rfl

theorem pinnedOdilyzko_all_verified :
    pinnedOdilyzkoVerifiedCount = pinnedOdilyzkoCertifiedCount := by
  norm_num [pinnedOdilyzkoVerifiedCount, pinnedOdilyzkoCertifiedCount]

noncomputable def pinnedMarshalOdilyzkoBatchCert : MarshalOdilyzkoBatchCert where
  verifiedCount := pinnedOdilyzkoVerifiedCount
  tolerance := pinnedOdilyzkoZAbsTolerance

theorem pinnedMarshal_odilyzko_batch_cert_count :
    marshalOdilyzkoCertCount pinnedMarshalOdilyzkoBatchCert = pinnedOdilyzkoVerifiedCount := rfl

end HPAnalysis
