#!/usr/bin/env python3
"""Emit/check MRS ladder Lean pins from engine JSON.

Usage:
  python tools/Analysis/EmitMarshalLadderCert.py
  python tools/Analysis/EmitMarshalLadderCert.py --check
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BSD = ROOT / "docs" / "generated" / "anavm_bsd_proof.json"
HODGE = ROOT / "docs" / "generated" / "anavm_hodge_proof.json"
GOLD = ROOT / "docs" / "generated" / "anavm_goldbach_proof.json"
OUT = ROOT / "docs" / "Formal" / "Analysis" / "LadderCertifiedBounds.lean"


def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def rat_num(x: float, denom: int = 10**6) -> str:
    n = int(round(x * denom))
    return f"({n} : ℝ) / {denom}"


def emit(bsd: dict, hodge: dict, gold: dict) -> str:
    l_gap = bsd.get("l_function_grid_rel_gap", 0.0)
    sha_gap = bsd.get("sha_resolvent_gap", 1.22)
    l_ub = bsd.get("l_function_grid_rel_gap_ub", 0.03)
    sha_ub = bsd.get("sha_resolvent_gap_ub", 2.0)
    major = gold.get("major_arc_spectral_mass", 0.55)
    minor = gold.get("minor_arc_bound", 0.005)
    major_th = gold.get("major_arc_threshold", 0.45)
    minor_ub = gold.get("minor_arc_ub", 0.01)

    return f"""import Analysis.CertifiedBounds
import Mathlib.Tactic

/-!
  AUTO-GENERATED by EmitMarshalLadderCert.py — do not edit by hand.
  Sources: anavm_bsd_proof.json, anavm_hodge_proof.json, anavm_goldbach_proof.json
-/

namespace HPAnalysis.Ladder

open Real

/-! ## BSD (curve 37a, GL(2)) -/

noncomputable def pinnedBSDAlgebraicRank : ℕ := {bsd.get('algebraic_rank', 1)}

noncomputable def pinnedBSDKernelMultiplicity : ℕ := {bsd.get('kernel_multiplicity', 1)}

noncomputable def pinnedBSDLGridRelGapUb : ℝ := {rat_num(l_ub, 100)}

noncomputable def pinnedBSDShaResolventGapUb : ℝ := {rat_num(sha_ub, 1)}

noncomputable def pinnedBSDLGridRelGapMeasured : ℝ := {rat_num(l_gap, 10**9)}

noncomputable def pinnedBSDShaResolventGapMeasured : ℝ := {rat_num(sha_gap, 10**6)}

theorem pinned_bsd_rank_match :
    pinnedBSDKernelMultiplicity = pinnedBSDAlgebraicRank := by
  norm_num [pinnedBSDKernelMultiplicity, pinnedBSDAlgebraicRank]

theorem pinned_bsd_l_grid_gap_bounded :
    pinnedBSDLGridRelGapMeasured < pinnedBSDLGridRelGapUb := by
  norm_num [pinnedBSDLGridRelGapMeasured, pinnedBSDLGridRelGapUb]

theorem pinned_bsd_sha_gap_bounded :
    pinnedBSDShaResolventGapMeasured < pinnedBSDShaResolventGapUb := by
  norm_num [pinnedBSDShaResolventGapMeasured, pinnedBSDShaResolventGapUb]

/-! ## Hodge (K3 stub, GL(3)) -/

noncomputable def pinnedHodgePredictedMultiplicity : ℕ := {hodge.get('predicted_hodge_multiplicity', 20)}

noncomputable def pinnedHodgeKernelMultiplicity : ℕ := {hodge.get('kernel_multiplicity', 20)}

theorem pinned_hodge_h11_match :
    pinnedHodgeKernelMultiplicity = pinnedHodgePredictedMultiplicity := by
  norm_num [pinnedHodgeKernelMultiplicity, pinnedHodgePredictedMultiplicity]

/-! ## Goldbach (GL(2) ellipse/Heegner) -/

noncomputable def pinnedGoldbachMajorArcThreshold : ℝ := {rat_num(major_th, 100)}

noncomputable def pinnedGoldbachMinorArcUb : ℝ := {rat_num(minor_ub, 100)}

noncomputable def pinnedGoldbachMajorArcMass : ℝ := {rat_num(major, 10**6)}

noncomputable def pinnedGoldbachMinorArcBound : ℝ := {rat_num(minor, 10**9)}

noncomputable def pinnedGoldbachN0 : ℕ := {gold.get('goldbach_n0', 4)}

theorem pinned_goldbach_major_arc_ok :
    pinnedGoldbachMajorArcThreshold ≤ pinnedGoldbachMajorArcMass := by
  norm_num [pinnedGoldbachMajorArcThreshold, pinnedGoldbachMajorArcMass]

theorem pinned_goldbach_minor_arc_ok :
    pinnedGoldbachMinorArcBound < pinnedGoldbachMinorArcUb := by
  norm_num [pinnedGoldbachMinorArcBound, pinnedGoldbachMinorArcUb]

end HPAnalysis.Ladder
"""


def check_engine(bsd: dict, hodge: dict, gold: dict) -> None:
    assert bsd["kernel_multiplicity"] == bsd["algebraic_rank"]
    assert bsd["l_function_grid_rel_gap"] < bsd["l_function_grid_rel_gap_ub"]
    assert bsd["sha_resolvent_gap"] < bsd["sha_resolvent_gap_ub"]
    assert hodge["kernel_multiplicity"] == hodge["predicted_hodge_multiplicity"]
    assert gold["major_arc_spectral_mass"] >= gold["major_arc_threshold"]
    assert gold["minor_arc_bound"] < gold["minor_arc_ub"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not BSD.exists() or not HODGE.exists() or not GOLD.exists():
        print("Missing ladder engine JSON under docs/generated/", file=sys.stderr)
        return 1

    bsd, hodge, gold = load(BSD), load(HODGE), load(GOLD)
    check_engine(bsd, hodge, gold)

    if args.check:
        print("EmitMarshalLadderCert: engine JSON bounds OK.")
        return 0

    OUT.write_text(emit(bsd, hodge, gold), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
