#!/usr/bin/env python3
"""Certify ζ(½+iγ)=0 via Marshal Riemann–Siegel (C++), sync Lean pins.

Pipeline:
  1. Marshal --ntz-generate --ntz-refine (coarse Odilyzko → Newton heights)
  2. marshal-zero-verify on refined one-line file
  3. Emit OdilyzkoZeroCertBridge.lean

Usage:
  python tools/Analysis/MarshalOdilyzkoZeroCert.py --run --count 10000
  python tools/Analysis/MarshalOdilyzkoZeroCert.py --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COARSE = ROOT / "tests" / "Fixtures" / "Zeros" / "NtzMergedOneLine.txt"
REFINED = ROOT / "docs" / "generated" / "NtzRefinedVerify.txt"
REFINED_CACHE = ROOT / "docs" / "generated" / "NtzRefinedVerify.zerocache"
OUT = ROOT / "docs" / "generated" / "marshal_odilyzko_zero_cert.json"
LEAN_PIN = ROOT / "docs" / "Formal" / "Analysis" / "OdilyzkoZeroCertBridge.lean"
VERIFY_BIN = ROOT / "build" / "marshal-zero-verify"
MARSHAL_BIN = ROOT / "build" / "Marshal"
if sys.platform == "win32":
    VERIFY_BIN = ROOT / "build" / "marshal-zero-verify.exe"
    MARSHAL_BIN = ROOT / "build" / "Marshal.exe"

DEFAULT_VERIFY_COUNT = 10_000
ZETA_ABS_TOL = 1e-10


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def run_ntz_refine(count: int, threads: int = 0) -> None:
    if not MARSHAL_BIN.is_file():
        raise FileNotFoundError(
            f"Missing {MARSHAL_BIN} — build with: cmake --build build --target Marshal"
        )
    REFINED.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        str(MARSHAL_BIN),
        "--ntz-generate",
        "--ntz-refine",
        "--ntz-input",
        str(COARSE),
        "--ntz-output",
        str(REFINED),
        "--ntz-cache",
        str(REFINED_CACHE),
        "--ntz-count",
        str(count),
        "--ntz-pad-to",
        str(count),
    ]
    if threads:
        cmd.extend(["--threads", str(threads)])
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if proc.stdout:
        sys.stderr.write(proc.stdout)
    if proc.stderr:
        sys.stderr.write(proc.stderr)
    if proc.returncode != 0 or not REFINED.is_file():
        raise RuntimeError(f"Marshal --ntz-generate failed (exit {proc.returncode})")


def run_marshal_verify(count: int, threads: int = 0) -> dict:
    if not VERIFY_BIN.is_file():
        raise FileNotFoundError(
            f"Missing {VERIFY_BIN} — build with: cmake --build build --target marshal-zero-verify"
        )
    cmd = [
        str(VERIFY_BIN),
        "--zeros",
        str(REFINED),
        "--count",
        str(count),
        "--tol",
        str(ZETA_ABS_TOL),
        "--output",
        str(OUT),
    ]
    if threads:
        cmd.extend(["--threads", str(threads)])
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if proc.stdout:
        sys.stderr.write(proc.stdout)
    if proc.stderr:
        sys.stderr.write(proc.stderr)
    if not OUT.is_file():
        raise RuntimeError(f"marshal-zero-verify failed (exit {proc.returncode})")
    cert = load_json(OUT)
    cert["coarse_source"] = str(COARSE)
    cert["refined_source"] = str(REFINED)
    OUT.write_text(json.dumps(cert, indent=2), encoding="utf-8")
    return cert


def emit_lean_pins(cert: dict) -> str:
    count = int(cert["certified_count"])
    verified = int(cert["verified_count"])
    tol = cert["z_abs_tolerance"]
    all_ok = verified == count and cert.get("all_verified", False)
    verified_thm = (
        "theorem pinnedOdilyzko_all_verified :\n"
        "    pinnedOdilyzkoVerifiedCount = pinnedOdilyzkoCertifiedCount := by\n"
        "  norm_num [pinnedOdilyzkoVerifiedCount, pinnedOdilyzkoCertifiedCount]\n"
        if all_ok
        else "def pinnedOdilyzko_batch_complete : Bool := false\n"
    )
    return f"""import Analysis.MarshalOdilyzkoZeroCert
import Mathlib.Tactic

/-!
  AUTO-GENERATED by tools/Analysis/MarshalOdilyzkoZeroCert.py — do not edit by hand.
  Pipeline: NtzGenerate(refine) → marshal-zero-verify → marshal_odilyzko_zero_cert.json
  Verified: {verified}/{count}
-/

namespace HPAnalysis

def pinnedOdilyzkoCertifiedCount : ℕ := {count}

def pinnedOdilyzkoVerifiedCount : ℕ := {verified}

noncomputable def pinnedOdilyzkoZAbsTolerance : ℝ := {tol}

theorem pinnedOdilyzko_cert_count_eq : pinnedOdilyzkoCertifiedCount = {count} := rfl

{verified_thm}
noncomputable def pinnedMarshalOdilyzkoBatchCert : MarshalOdilyzkoBatchCert where
  verifiedCount := pinnedOdilyzkoVerifiedCount
  tolerance := pinnedOdilyzkoZAbsTolerance

theorem pinnedMarshal_odilyzko_batch_cert_count :
    marshalOdilyzkoCertCount pinnedMarshalOdilyzkoBatchCert = pinnedOdilyzkoVerifiedCount := rfl

end HPAnalysis
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Odilyzko zeta-zero cert (Marshal C++)")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--run", action="store_true", help="Refine + verify + emit Lean pins")
    parser.add_argument("--count", type=int, default=DEFAULT_VERIFY_COUNT)
    parser.add_argument("--threads", type=int, default=0)
    parser.add_argument("--skip-refine", action="store_true", help="Verify existing refined file only")
    args = parser.parse_args()

    if not COARSE.is_file():
        print(f"FAIL: missing {COARSE}", file=sys.stderr)
        return 1

    if args.run or (not args.check and not OUT.is_file()):
        if not args.skip_refine:
            run_ntz_refine(args.count, args.threads)
        cert = run_marshal_verify(args.count, args.threads)
        LEAN_PIN.write_text(emit_lean_pins(cert), encoding="utf-8")
        print(f"Wrote {REFINED}, {OUT}, {LEAN_PIN}")
        if not cert.get("all_verified"):
            print(
                f"WARN: partial verify {cert['verified_count']}/{cert['certified_count']} "
                f"(failed_index={cert.get('failed_index')})",
                file=sys.stderr,
            )
            return 1

    if not OUT.is_file():
        print(f"FAIL: missing {OUT} — run with --run", file=sys.stderr)
        return 1

    cert = load_json(OUT)
    if args.check:
        if not cert.get("all_verified"):
            print("FAIL: Odilyzko cert all_verified=false", file=sys.stderr)
            return 1
        if cert.get("engine") != "marshal_riemann_siegel":
            print("FAIL: cert engine must be marshal_riemann_siegel", file=sys.stderr)
            return 1
        if not REFINED.is_file():
            print(f"FAIL: missing refined zeros {REFINED}", file=sys.stderr)
            return 1
        if not LEAN_PIN.is_file():
            print(f"FAIL: missing {LEAN_PIN}", file=sys.stderr)
            return 1
        expected_count = f"pinnedOdilyzkoCertifiedCount : ℕ := {cert['certified_count']}"
        if expected_count not in LEAN_PIN.read_text(encoding="utf-8"):
            print("FAIL: Lean pin out of sync — run with --run", file=sys.stderr)
            return 1
        print(
            f"Marshal Odilyzko cert OK: verified={cert['verified_count']}/"
            f"{cert['certified_count']} max|Z|={cert['max_z_abs_refined']:.3e}"
        )
        return 0

    print(json.dumps({k: cert[k] for k in cert if k != "head_samples"}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
