#!/usr/bin/env python3
"""Mechanical sync: keep summability spine in GenusOneLogBoundsTail; envelope lemmas are autogenerated."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TAIL = ROOT / "docs" / "Formal" / "Analysis" / "GenusOneLogBoundsTail.lean"
MARKER = "private lemma norm_sub_log_sub_one_le_at_R"
SUMMABILITY = "theorem marshal_genus_one_log_summability_proved"


def main() -> int:
    text = TAIL.read_text(encoding="utf-8")
    if MARKER in text:
        prefix = text.split(MARKER)[0].rstrip()
    else:
        prefix = text
    summ_match = re.search(
        rf"({re.escape(SUMMABILITY)}[\s\S]*?)\nend HPAnalysis",
        text,
    )
    if not summ_match:
        print("SyncGenusOneLogTailLean: missing summability theorem", file=sys.stderr)
        return 1
    bridge = """
import Analysis.MarshalGenusOneLogAnalyticBridge

export MarshalGenusOneLogAnalyticBridge (
  weierstrass_log_norm_le_head_envelope_small
  weierstrass_log_norm_le_head_envelope_ratio
  weierstrass_log_norm_le_head_envelope)
"""
    if "import Analysis.MarshalGenusOneLogAnalyticBridge" not in prefix:
        prefix = prefix.replace(
            "import Mathlib.Topology.Compactness.Compact\n",
            "import Mathlib.Topology.Compactness.Compact\n" + bridge,
        )
    out = prefix + "\n\n" + summ_match.group(1) + "\n\nend HPAnalysis\n"
    if out != text:
        TAIL.write_text(out, encoding="utf-8")
        print(f"SyncGenusOneLogTailLean: updated {TAIL}")
    else:
        print(f"SyncGenusOneLogTailLean: {TAIL} already synced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
